// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: global/combat.proto

package global

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 战斗单位信息
type EntityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroTypeId    int32   `protobuf:"varint,1,opt,name=HeroTypeId,proto3" json:"HeroTypeId,omitempty"`              // 英雄type_id
	CrystalSkills []int32 `protobuf:"varint,2,rep,packed,name=CrystalSkills,proto3" json:"CrystalSkills,omitempty"` // 残响技能
	AttValue      []int32 `protobuf:"varint,3,rep,packed,name=AttValue,proto3" json:"AttValue,omitempty"`           // 英雄属性
}

func (x *EntityInfo) Reset() {
	*x = EntityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_combat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo) ProtoMessage() {}

func (x *EntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_global_combat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo.ProtoReflect.Descriptor instead.
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return file_global_combat_proto_rawDescGZIP(), []int{0}
}

func (x *EntityInfo) GetHeroTypeId() int32 {
	if x != nil {
		return x.HeroTypeId
	}
	return 0
}

func (x *EntityInfo) GetCrystalSkills() []int32 {
	if x != nil {
		return x.CrystalSkills
	}
	return nil
}

func (x *EntityInfo) GetAttValue() []int32 {
	if x != nil {
		return x.AttValue
	}
	return nil
}

var File_global_combat_proto protoreflect.FileDescriptor

var file_global_combat_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x22, 0x6e, 0x0a,
	0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x48,
	0x65, 0x72, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x48, 0x65, 0x72, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43,
	0x72, 0x79, 0x73, 0x74, 0x61, 0x6c, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x0d, 0x43, 0x72, 0x79, 0x73, 0x74, 0x61, 0x6c, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x74, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x08, 0x41, 0x74, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x34, 0x5a,
	0x29, 0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x66,
	0x75, 0x6e, 0x70, 0x6c, 0x75, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0xaa, 0x02, 0x06, 0x67, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_global_combat_proto_rawDescOnce sync.Once
	file_global_combat_proto_rawDescData = file_global_combat_proto_rawDesc
)

func file_global_combat_proto_rawDescGZIP() []byte {
	file_global_combat_proto_rawDescOnce.Do(func() {
		file_global_combat_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_combat_proto_rawDescData)
	})
	return file_global_combat_proto_rawDescData
}

var file_global_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_global_combat_proto_goTypes = []interface{}{
	(*EntityInfo)(nil), // 0: global.EntityInfo
}
var file_global_combat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_global_combat_proto_init() }
func file_global_combat_proto_init() {
	if File_global_combat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_global_combat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_combat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_combat_proto_goTypes,
		DependencyIndexes: file_global_combat_proto_depIdxs,
		MessageInfos:      file_global_combat_proto_msgTypes,
	}.Build()
	File_global_combat_proto = out.File
	file_global_combat_proto_rawDesc = nil
	file_global_combat_proto_goTypes = nil
	file_global_combat_proto_depIdxs = nil
}
