// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: global/player.proto

package global

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type C2S_CreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *C2S_CreatePlayer) Reset() {
	*x = C2S_CreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_CreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CreatePlayer) ProtoMessage() {}

func (x *C2S_CreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_global_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CreatePlayer.ProtoReflect.Descriptor instead.
func (*C2S_CreatePlayer) Descriptor() ([]byte, []int) {
	return file_global_player_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_CreatePlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type S2C_CreatePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *S2C_CreatePlayer) Reset() {
	*x = S2C_CreatePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_CreatePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CreatePlayer) ProtoMessage() {}

func (x *S2C_CreatePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_global_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CreatePlayer.ProtoReflect.Descriptor instead.
func (*S2C_CreatePlayer) Descriptor() ([]byte, []int) {
	return file_global_player_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_CreatePlayer) GetInfo() *PlayerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type C2S_QueryPlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_QueryPlayerInfo) Reset() {
	*x = C2S_QueryPlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_QueryPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_QueryPlayerInfo) ProtoMessage() {}

func (x *C2S_QueryPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_global_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_QueryPlayerInfo.ProtoReflect.Descriptor instead.
func (*C2S_QueryPlayerInfo) Descriptor() ([]byte, []int) {
	return file_global_player_proto_rawDescGZIP(), []int{2}
}

type S2C_QueryPlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info  *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error int32       `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *S2C_QueryPlayerInfo) Reset() {
	*x = S2C_QueryPlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_QueryPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_QueryPlayerInfo) ProtoMessage() {}

func (x *S2C_QueryPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_global_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_QueryPlayerInfo.ProtoReflect.Descriptor instead.
func (*S2C_QueryPlayerInfo) Descriptor() ([]byte, []int) {
	return file_global_player_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_QueryPlayerInfo) GetInfo() *PlayerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *S2C_QueryPlayerInfo) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

type S2C_ExpUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exp   int32 `protobuf:"varint,1,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Level int32 `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
}

func (x *S2C_ExpUpdate) Reset() {
	*x = S2C_ExpUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_player_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_ExpUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ExpUpdate) ProtoMessage() {}

func (x *S2C_ExpUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_global_player_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ExpUpdate.ProtoReflect.Descriptor instead.
func (*S2C_ExpUpdate) Descriptor() ([]byte, []int) {
	return file_global_player_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_ExpUpdate) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *S2C_ExpUpdate) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// gm 命令:
// gm player level 10
// gm hero add 1
// gm item add 1 10
type C2S_GmCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
}

func (x *C2S_GmCmd) Reset() {
	*x = C2S_GmCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_player_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_GmCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GmCmd) ProtoMessage() {}

func (x *C2S_GmCmd) ProtoReflect() protoreflect.Message {
	mi := &file_global_player_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GmCmd.ProtoReflect.Descriptor instead.
func (*C2S_GmCmd) Descriptor() ([]byte, []int) {
	return file_global_player_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_GmCmd) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

var File_global_player_proto protoreflect.FileDescriptor

var file_global_player_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x1a, 0x13, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x10, 0x53, 0x32,
	0x43, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x26,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x32, 0x53, 0x5f, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x53, 0x0a,
	0x13, 0x53, 0x32, 0x43, 0x5f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x5f, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x45, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x1d, 0x0a, 0x09, 0x43,
	0x32, 0x53, 0x5f, 0x47, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x42, 0x34, 0x5a, 0x29, 0x62, 0x69,
	0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x66, 0x75, 0x6e, 0x70,
	0x6c, 0x75, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0xaa, 0x02, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_global_player_proto_rawDescOnce sync.Once
	file_global_player_proto_rawDescData = file_global_player_proto_rawDesc
)

func file_global_player_proto_rawDescGZIP() []byte {
	file_global_player_proto_rawDescOnce.Do(func() {
		file_global_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_player_proto_rawDescData)
	})
	return file_global_player_proto_rawDescData
}

var file_global_player_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_global_player_proto_goTypes = []interface{}{
	(*C2S_CreatePlayer)(nil),    // 0: global.C2S_CreatePlayer
	(*S2C_CreatePlayer)(nil),    // 1: global.S2C_CreatePlayer
	(*C2S_QueryPlayerInfo)(nil), // 2: global.C2S_QueryPlayerInfo
	(*S2C_QueryPlayerInfo)(nil), // 3: global.S2C_QueryPlayerInfo
	(*S2C_ExpUpdate)(nil),       // 4: global.S2C_ExpUpdate
	(*C2S_GmCmd)(nil),           // 5: global.C2S_GmCmd
	(*PlayerInfo)(nil),          // 6: global.PlayerInfo
}
var file_global_player_proto_depIdxs = []int32{
	6, // 0: global.S2C_CreatePlayer.info:type_name -> global.PlayerInfo
	6, // 1: global.S2C_QueryPlayerInfo.info:type_name -> global.PlayerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_global_player_proto_init() }
func file_global_player_proto_init() {
	if File_global_player_proto != nil {
		return
	}
	file_global_define_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_global_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_CreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_CreatePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_QueryPlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_QueryPlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_player_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_ExpUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_player_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_GmCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_player_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_player_proto_goTypes,
		DependencyIndexes: file_global_player_proto_depIdxs,
		MessageInfos:      file_global_player_proto_msgTypes,
	}.Build()
	File_global_player_proto = out.File
	file_global_player_proto_rawDesc = nil
	file_global_player_proto_goTypes = nil
	file_global_player_proto_depIdxs = nil
}
