// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pubsub/pubsub.proto

package pubsub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	account "github.com/yokaiio/yokai_server/proto/account"
	game "github.com/yokaiio/yokai_server/proto/game"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/////////////////////////////////////////////////
// pub/sub
/////////////////////////////////////////////////
type PubStartGate struct {
	Info                 *account.LiteAccount `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PubStartGate) Reset()         { *m = PubStartGate{} }
func (m *PubStartGate) String() string { return proto.CompactTextString(m) }
func (*PubStartGate) ProtoMessage()    {}
func (*PubStartGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce310d0bb9f289ed, []int{0}
}

func (m *PubStartGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubStartGate.Unmarshal(m, b)
}
func (m *PubStartGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubStartGate.Marshal(b, m, deterministic)
}
func (m *PubStartGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubStartGate.Merge(m, src)
}
func (m *PubStartGate) XXX_Size() int {
	return xxx_messageInfo_PubStartGate.Size(m)
}
func (m *PubStartGate) XXX_DiscardUnknown() {
	xxx_messageInfo_PubStartGate.DiscardUnknown(m)
}

var xxx_messageInfo_PubStartGate proto.InternalMessageInfo

func (m *PubStartGate) GetInfo() *account.LiteAccount {
	if m != nil {
		return m.Info
	}
	return nil
}

type PubGateResult struct {
	Info                 *account.LiteAccount `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Win                  bool                 `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PubGateResult) Reset()         { *m = PubGateResult{} }
func (m *PubGateResult) String() string { return proto.CompactTextString(m) }
func (*PubGateResult) ProtoMessage()    {}
func (*PubGateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce310d0bb9f289ed, []int{1}
}

func (m *PubGateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubGateResult.Unmarshal(m, b)
}
func (m *PubGateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubGateResult.Marshal(b, m, deterministic)
}
func (m *PubGateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubGateResult.Merge(m, src)
}
func (m *PubGateResult) XXX_Size() int {
	return xxx_messageInfo_PubGateResult.Size(m)
}
func (m *PubGateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PubGateResult.DiscardUnknown(m)
}

var xxx_messageInfo_PubGateResult proto.InternalMessageInfo

func (m *PubGateResult) GetInfo() *account.LiteAccount {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PubGateResult) GetWin() bool {
	if m != nil {
		return m.Win
	}
	return false
}

type PubSyncPlayerInfo struct {
	Info                 *game.PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PubSyncPlayerInfo) Reset()         { *m = PubSyncPlayerInfo{} }
func (m *PubSyncPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PubSyncPlayerInfo) ProtoMessage()    {}
func (*PubSyncPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce310d0bb9f289ed, []int{2}
}

func (m *PubSyncPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubSyncPlayerInfo.Unmarshal(m, b)
}
func (m *PubSyncPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubSyncPlayerInfo.Marshal(b, m, deterministic)
}
func (m *PubSyncPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubSyncPlayerInfo.Merge(m, src)
}
func (m *PubSyncPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PubSyncPlayerInfo.Size(m)
}
func (m *PubSyncPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PubSyncPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PubSyncPlayerInfo proto.InternalMessageInfo

func (m *PubSyncPlayerInfo) GetInfo() *game.PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*PubStartGate)(nil), "yokai_pubsub.PubStartGate")
	proto.RegisterType((*PubGateResult)(nil), "yokai_pubsub.PubGateResult")
	proto.RegisterType((*PubSyncPlayerInfo)(nil), "yokai_pubsub.PubSyncPlayerInfo")
}

func init() { proto.RegisterFile("pubsub/pubsub.proto", fileDescriptor_ce310d0bb9f289ed) }

var fileDescriptor_ce310d0bb9f289ed = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x31, 0x4b, 0xc7, 0x30,
	0x10, 0x47, 0xa9, 0x8a, 0x48, 0xac, 0x60, 0x2b, 0x4a, 0xe9, 0x54, 0x3a, 0x15, 0x91, 0x04, 0x74,
	0x57, 0x74, 0x11, 0xc1, 0xa1, 0xd6, 0xcd, 0xa5, 0x24, 0x21, 0xd6, 0x60, 0x9b, 0x94, 0xf4, 0xa2,
	0xf4, 0xdb, 0x4b, 0x72, 0x15, 0x71, 0xfc, 0x4f, 0xbf, 0xcb, 0xf1, 0xf2, 0xb8, 0x3b, 0x72, 0x36,
	0x7b, 0xb1, 0x78, 0xc1, 0x30, 0xe8, 0xec, 0x2c, 0xd8, 0x3c, 0x5d, 0xed, 0x27, 0xd7, 0x3d, 0xf6,
	0xca, 0x73, 0x2e, 0xa5, 0xf5, 0x06, 0xd8, 0x96, 0x08, 0x95, 0xd9, 0xc0, 0x27, 0xc5, 0xe6, 0x91,
	0xaf, 0xca, 0x61, 0xab, 0xbe, 0x25, 0x69, 0xeb, 0xc5, 0x2b, 0x70, 0x07, 0x8f, 0x1c, 0x54, 0x4e,
	0xc9, 0x81, 0x36, 0xef, 0xb6, 0x48, 0xaa, 0xa4, 0x39, 0xbe, 0x2e, 0x29, 0x6a, 0x7f, 0x35, 0xcf,
	0x1a, 0xd4, 0x3d, 0xd6, 0x5d, 0xe4, 0xea, 0x17, 0x72, 0xd2, 0x7a, 0x11, 0xbe, 0x76, 0x6a, 0xf1,
	0x23, 0xec, 0x2a, 0xc8, 0x4f, 0xc9, 0xfe, 0xb7, 0x36, 0xc5, 0x5e, 0x95, 0x34, 0x47, 0x5d, 0x28,
	0xeb, 0x3b, 0x92, 0x85, 0x91, 0x56, 0x23, 0xdb, 0x38, 0xe9, 0x53, 0xc0, 0x2e, 0xff, 0x69, 0x2f,
	0x36, 0x6d, 0xd8, 0x87, 0xfe, 0x51, 0xa8, 0x7c, 0xa0, 0x6f, 0x57, 0x83, 0x86, 0x0f, 0x2f, 0xa8,
	0xb4, 0x13, 0x8b, 0xa4, 0xb6, 0x98, 0xfd, 0xa2, 0xdc, 0x97, 0x72, 0x2c, 0x2e, 0xbf, 0x5d, 0x50,
	0x1c, 0xc6, 0xd7, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x5c, 0xbb, 0xa1, 0x59, 0x01,
	0x00, 0x00,
}
