// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/att.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// Att
type Att struct {
	Value                []int64  `protobuf:"varint,1,rep,packed,name=Value,proto3" json:"Value,omitempty"`
	ExValue              []int64  `protobuf:"varint,2,rep,packed,name=ExValue,proto3" json:"ExValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Att) Reset()         { *m = Att{} }
func (m *Att) String() string { return proto.CompactTextString(m) }
func (*Att) ProtoMessage()    {}
func (*Att) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b8149fbf8c0a13, []int{0}
}

func (m *Att) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Att.Unmarshal(m, b)
}
func (m *Att) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Att.Marshal(b, m, deterministic)
}
func (m *Att) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Att.Merge(m, src)
}
func (m *Att) XXX_Size() int {
	return xxx_messageInfo_Att.Size(m)
}
func (m *Att) XXX_DiscardUnknown() {
	xxx_messageInfo_Att.DiscardUnknown(m)
}

var xxx_messageInfo_Att proto.InternalMessageInfo

func (m *Att) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Att) GetExValue() []int64 {
	if m != nil {
		return m.ExValue
	}
	return nil
}

func init() {
	proto.RegisterType((*Att)(nil), "yokai_game.Att")
}

func init() { proto.RegisterFile("game/att.proto", fileDescriptor_38b8149fbf8c0a13) }

var fileDescriptor_38b8149fbf8c0a13 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4f, 0xcc, 0x4d,
	0xd5, 0x4f, 0x2c, 0x29, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xaa, 0xcc, 0xcf, 0x4e,
	0xcc, 0x8c, 0x07, 0x89, 0x2a, 0x99, 0x72, 0x31, 0x3b, 0x96, 0x94, 0x08, 0x89, 0x70, 0xb1, 0x86,
	0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6b, 0x30, 0x07, 0x41, 0x38, 0x42, 0x12, 0x5c,
	0xec, 0xae, 0x15, 0x10, 0x71, 0x26, 0xb0, 0x38, 0x8c, 0xeb, 0xa4, 0x13, 0xa5, 0x95, 0x9e, 0x59,
	0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x0f, 0x36, 0x2f, 0x33, 0x1f, 0x42, 0xc7, 0x17,
	0xa7, 0x16, 0x95, 0xa5, 0x16, 0xe9, 0x83, 0xed, 0xd2, 0x07, 0x59, 0x92, 0xc4, 0x06, 0x66, 0x1b,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xe2, 0x41, 0xf8, 0x89, 0x00, 0x00, 0x00,
}
