// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/game.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	account "github.com/yokaiio/yokai_server/proto/account"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRemoteLiteAccountRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRemoteLiteAccountRequest) Reset()         { *m = GetRemoteLiteAccountRequest{} }
func (m *GetRemoteLiteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetRemoteLiteAccountRequest) ProtoMessage()    {}
func (*GetRemoteLiteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{0}
}

func (m *GetRemoteLiteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteLiteAccountRequest.Unmarshal(m, b)
}
func (m *GetRemoteLiteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteLiteAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetRemoteLiteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteLiteAccountRequest.Merge(m, src)
}
func (m *GetRemoteLiteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetRemoteLiteAccountRequest.Size(m)
}
func (m *GetRemoteLiteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteLiteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteLiteAccountRequest proto.InternalMessageInfo

func (m *GetRemoteLiteAccountRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRemoteLiteAccountReply struct {
	Info                 *account.LiteAccount `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetRemoteLiteAccountReply) Reset()         { *m = GetRemoteLiteAccountReply{} }
func (m *GetRemoteLiteAccountReply) String() string { return proto.CompactTextString(m) }
func (*GetRemoteLiteAccountReply) ProtoMessage()    {}
func (*GetRemoteLiteAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{1}
}

func (m *GetRemoteLiteAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteLiteAccountReply.Unmarshal(m, b)
}
func (m *GetRemoteLiteAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteLiteAccountReply.Marshal(b, m, deterministic)
}
func (m *GetRemoteLiteAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteLiteAccountReply.Merge(m, src)
}
func (m *GetRemoteLiteAccountReply) XXX_Size() int {
	return xxx_messageInfo_GetRemoteLiteAccountReply.Size(m)
}
func (m *GetRemoteLiteAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteLiteAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteLiteAccountReply proto.InternalMessageInfo

func (m *GetRemoteLiteAccountReply) GetInfo() *account.LiteAccount {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetRemoteLitePlayerRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRemoteLitePlayerRequest) Reset()         { *m = GetRemoteLitePlayerRequest{} }
func (m *GetRemoteLitePlayerRequest) String() string { return proto.CompactTextString(m) }
func (*GetRemoteLitePlayerRequest) ProtoMessage()    {}
func (*GetRemoteLitePlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{2}
}

func (m *GetRemoteLitePlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteLitePlayerRequest.Unmarshal(m, b)
}
func (m *GetRemoteLitePlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteLitePlayerRequest.Marshal(b, m, deterministic)
}
func (m *GetRemoteLitePlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteLitePlayerRequest.Merge(m, src)
}
func (m *GetRemoteLitePlayerRequest) XXX_Size() int {
	return xxx_messageInfo_GetRemoteLitePlayerRequest.Size(m)
}
func (m *GetRemoteLitePlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteLitePlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteLitePlayerRequest proto.InternalMessageInfo

func (m *GetRemoteLitePlayerRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRemoteLitePlayerReply struct {
	Info                 *LitePlayer `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRemoteLitePlayerReply) Reset()         { *m = GetRemoteLitePlayerReply{} }
func (m *GetRemoteLitePlayerReply) String() string { return proto.CompactTextString(m) }
func (*GetRemoteLitePlayerReply) ProtoMessage()    {}
func (*GetRemoteLitePlayerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{3}
}

func (m *GetRemoteLitePlayerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteLitePlayerReply.Unmarshal(m, b)
}
func (m *GetRemoteLitePlayerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteLitePlayerReply.Marshal(b, m, deterministic)
}
func (m *GetRemoteLitePlayerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteLitePlayerReply.Merge(m, src)
}
func (m *GetRemoteLitePlayerReply) XXX_Size() int {
	return xxx_messageInfo_GetRemoteLitePlayerReply.Size(m)
}
func (m *GetRemoteLitePlayerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteLitePlayerReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteLitePlayerReply proto.InternalMessageInfo

func (m *GetRemoteLitePlayerReply) GetInfo() *LitePlayer {
	if m != nil {
		return m.Info
	}
	return nil
}

type UpdatePlayerExpRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlayerExpRequest) Reset()         { *m = UpdatePlayerExpRequest{} }
func (m *UpdatePlayerExpRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerExpRequest) ProtoMessage()    {}
func (*UpdatePlayerExpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{4}
}

func (m *UpdatePlayerExpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerExpRequest.Unmarshal(m, b)
}
func (m *UpdatePlayerExpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerExpRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerExpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerExpRequest.Merge(m, src)
}
func (m *UpdatePlayerExpRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerExpRequest.Size(m)
}
func (m *UpdatePlayerExpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerExpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerExpRequest proto.InternalMessageInfo

func (m *UpdatePlayerExpRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdatePlayerExpReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Exp                  int64    `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlayerExpReply) Reset()         { *m = UpdatePlayerExpReply{} }
func (m *UpdatePlayerExpReply) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerExpReply) ProtoMessage()    {}
func (*UpdatePlayerExpReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{5}
}

func (m *UpdatePlayerExpReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerExpReply.Unmarshal(m, b)
}
func (m *UpdatePlayerExpReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerExpReply.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerExpReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerExpReply.Merge(m, src)
}
func (m *UpdatePlayerExpReply) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerExpReply.Size(m)
}
func (m *UpdatePlayerExpReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerExpReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerExpReply proto.InternalMessageInfo

func (m *UpdatePlayerExpReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePlayerExpReply) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRemoteLiteAccountRequest)(nil), "yokai_game.GetRemoteLiteAccountRequest")
	proto.RegisterType((*GetRemoteLiteAccountReply)(nil), "yokai_game.GetRemoteLiteAccountReply")
	proto.RegisterType((*GetRemoteLitePlayerRequest)(nil), "yokai_game.GetRemoteLitePlayerRequest")
	proto.RegisterType((*GetRemoteLitePlayerReply)(nil), "yokai_game.GetRemoteLitePlayerReply")
	proto.RegisterType((*UpdatePlayerExpRequest)(nil), "yokai_game.UpdatePlayerExpRequest")
	proto.RegisterType((*UpdatePlayerExpReply)(nil), "yokai_game.UpdatePlayerExpReply")
}

func init() { proto.RegisterFile("game/game.proto", fileDescriptor_2a9278d664c0c01e) }

var fileDescriptor_2a9278d664c0c01e = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4f, 0xc2, 0x30,
	0x18, 0xc6, 0x65, 0x18, 0x0f, 0x2f, 0x89, 0x68, 0x45, 0x82, 0xf5, 0x42, 0x16, 0xff, 0x10, 0x82,
	0x5d, 0x82, 0x17, 0xaf, 0x9a, 0x28, 0x07, 0x3d, 0x18, 0x8c, 0x07, 0xbd, 0x90, 0x32, 0x5e, 0xa1,
	0x91, 0xd1, 0x3a, 0x3a, 0xc2, 0x3e, 0x9a, 0xdf, 0xce, 0xac, 0x95, 0xb8, 0xe1, 0x06, 0x97, 0xb5,
	0x79, 0xf3, 0x7b, 0xfa, 0x3c, 0x79, 0xf6, 0x42, 0x75, 0xcc, 0x03, 0xf4, 0x92, 0x0f, 0x53, 0xa1,
	0xd4, 0x92, 0x40, 0x2c, 0x3f, 0xb9, 0x18, 0x24, 0x13, 0x7a, 0xcc, 0x7d, 0x5f, 0x46, 0x33, 0xed,
	0xfd, 0x9e, 0x16, 0xa1, 0x87, 0x46, 0xa3, 0xa6, 0x3c, 0xc6, 0xd0, 0x8e, 0xdc, 0x2b, 0x38, 0xed,
	0xa1, 0xee, 0x63, 0x20, 0x35, 0x3e, 0x09, 0x8d, 0xb7, 0x56, 0xd0, 0xc7, 0xaf, 0x08, 0xe7, 0x9a,
	0xec, 0x83, 0x23, 0x46, 0x8d, 0x52, 0xb3, 0xd4, 0x2a, 0xf7, 0x1d, 0x31, 0x72, 0x1f, 0xe1, 0x24,
	0x1f, 0x57, 0xd3, 0x98, 0x30, 0xd8, 0x15, 0xb3, 0x0f, 0x69, 0xf0, 0x4a, 0x97, 0x32, 0x1b, 0x68,
	0x15, 0x21, 0x8d, 0x1b, 0xce, 0xed, 0x00, 0xcd, 0x3c, 0xf6, 0x6c, 0x82, 0x15, 0x59, 0x3f, 0x40,
	0x23, 0x97, 0x4e, 0x9c, 0xdb, 0x19, 0xe7, 0x3a, 0xfb, 0xab, 0x82, 0xa5, 0x50, 0xeb, 0xda, 0x82,
	0xfa, 0xab, 0x1a, 0xf1, 0xd5, 0xf4, 0x7e, 0xa9, 0x8a, 0x1c, 0x6f, 0xa0, 0xf6, 0x8f, 0x4c, 0xdc,
	0xd6, 0x38, 0x72, 0x00, 0x65, 0x5c, 0xaa, 0x86, 0x63, 0x06, 0xc9, 0xb5, 0xfb, 0xed, 0x40, 0xa5,
	0xc7, 0x03, 0x7c, 0xc1, 0x70, 0x21, 0x7c, 0x24, 0x13, 0xa8, 0xe5, 0xd5, 0x46, 0x2e, 0xd3, 0x49,
	0x37, 0xfc, 0x07, 0x7a, 0xbe, 0x1d, 0x54, 0xd3, 0xd8, 0xdd, 0x21, 0x08, 0x47, 0x39, 0x2d, 0x91,
	0x8b, 0x42, 0x7d, 0xa6, 0x74, 0x7a, 0xb6, 0x95, 0xb3, 0x36, 0x6f, 0x50, 0x5d, 0xab, 0x86, 0xb8,
	0x69, 0x69, 0x7e, 0xc3, 0xb4, 0xb9, 0x91, 0x31, 0x4f, 0xdf, 0x75, 0xde, 0xdb, 0x63, 0xa1, 0x27,
	0xd1, 0x90, 0xf9, 0x32, 0xf0, 0x0c, 0x2f, 0xa4, 0x3d, 0x07, 0x73, 0x0c, 0x17, 0x18, 0x7a, 0x66,
	0x75, 0xcd, 0xee, 0x0f, 0xf7, 0xcc, 0xfd, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x17, 0x68, 0x2e,
	0x6e, 0x0f, 0x03, 0x00, 0x00,
}
