// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/hero.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// Hero
type Hero struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TypeId               int32    `protobuf:"varint,2,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	Exp                  int64    `protobuf:"varint,3,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	EquipList            []int64  `protobuf:"varint,5,rep,packed,name=EquipList,proto3" json:"EquipList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{0}
}

func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (m *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(m, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hero) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Hero) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Hero) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Hero) GetEquipList() []int64 {
	if m != nil {
		return m.EquipList
	}
	return nil
}

type C2M_AddHero struct {
	TypeId               int32    `protobuf:"varint,1,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_AddHero) Reset()         { *m = C2M_AddHero{} }
func (m *C2M_AddHero) String() string { return proto.CompactTextString(m) }
func (*C2M_AddHero) ProtoMessage()    {}
func (*C2M_AddHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{1}
}

func (m *C2M_AddHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_AddHero.Unmarshal(m, b)
}
func (m *C2M_AddHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_AddHero.Marshal(b, m, deterministic)
}
func (m *C2M_AddHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_AddHero.Merge(m, src)
}
func (m *C2M_AddHero) XXX_Size() int {
	return xxx_messageInfo_C2M_AddHero.Size(m)
}
func (m *C2M_AddHero) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_AddHero.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_AddHero proto.InternalMessageInfo

func (m *C2M_AddHero) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type C2M_DelHero struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_DelHero) Reset()         { *m = C2M_DelHero{} }
func (m *C2M_DelHero) String() string { return proto.CompactTextString(m) }
func (*C2M_DelHero) ProtoMessage()    {}
func (*C2M_DelHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{2}
}

func (m *C2M_DelHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_DelHero.Unmarshal(m, b)
}
func (m *C2M_DelHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_DelHero.Marshal(b, m, deterministic)
}
func (m *C2M_DelHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_DelHero.Merge(m, src)
}
func (m *C2M_DelHero) XXX_Size() int {
	return xxx_messageInfo_C2M_DelHero.Size(m)
}
func (m *C2M_DelHero) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_DelHero.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_DelHero proto.InternalMessageInfo

func (m *C2M_DelHero) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type C2M_QueryHeros struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryHeros) Reset()         { *m = C2M_QueryHeros{} }
func (m *C2M_QueryHeros) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryHeros) ProtoMessage()    {}
func (*C2M_QueryHeros) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{3}
}

func (m *C2M_QueryHeros) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryHeros.Unmarshal(m, b)
}
func (m *C2M_QueryHeros) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryHeros.Marshal(b, m, deterministic)
}
func (m *C2M_QueryHeros) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryHeros.Merge(m, src)
}
func (m *C2M_QueryHeros) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryHeros.Size(m)
}
func (m *C2M_QueryHeros) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryHeros.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryHeros proto.InternalMessageInfo

type M2C_HeroUpdate struct {
	Info                 *Hero    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_HeroUpdate) Reset()         { *m = M2C_HeroUpdate{} }
func (m *M2C_HeroUpdate) String() string { return proto.CompactTextString(m) }
func (*M2C_HeroUpdate) ProtoMessage()    {}
func (*M2C_HeroUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{4}
}

func (m *M2C_HeroUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_HeroUpdate.Unmarshal(m, b)
}
func (m *M2C_HeroUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_HeroUpdate.Marshal(b, m, deterministic)
}
func (m *M2C_HeroUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_HeroUpdate.Merge(m, src)
}
func (m *M2C_HeroUpdate) XXX_Size() int {
	return xxx_messageInfo_M2C_HeroUpdate.Size(m)
}
func (m *M2C_HeroUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_HeroUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_HeroUpdate proto.InternalMessageInfo

func (m *M2C_HeroUpdate) GetInfo() *Hero {
	if m != nil {
		return m.Info
	}
	return nil
}

type M2C_HeroList struct {
	Heros                []*Hero  `protobuf:"bytes,1,rep,name=heros,proto3" json:"heros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_HeroList) Reset()         { *m = M2C_HeroList{} }
func (m *M2C_HeroList) String() string { return proto.CompactTextString(m) }
func (*M2C_HeroList) ProtoMessage()    {}
func (*M2C_HeroList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{5}
}

func (m *M2C_HeroList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_HeroList.Unmarshal(m, b)
}
func (m *M2C_HeroList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_HeroList.Marshal(b, m, deterministic)
}
func (m *M2C_HeroList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_HeroList.Merge(m, src)
}
func (m *M2C_HeroList) XXX_Size() int {
	return xxx_messageInfo_M2C_HeroList.Size(m)
}
func (m *M2C_HeroList) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_HeroList.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_HeroList proto.InternalMessageInfo

func (m *M2C_HeroList) GetHeros() []*Hero {
	if m != nil {
		return m.Heros
	}
	return nil
}

type M2C_HeroInfo struct {
	Info                 *Hero    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_HeroInfo) Reset()         { *m = M2C_HeroInfo{} }
func (m *M2C_HeroInfo) String() string { return proto.CompactTextString(m) }
func (*M2C_HeroInfo) ProtoMessage()    {}
func (*M2C_HeroInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{6}
}

func (m *M2C_HeroInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_HeroInfo.Unmarshal(m, b)
}
func (m *M2C_HeroInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_HeroInfo.Marshal(b, m, deterministic)
}
func (m *M2C_HeroInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_HeroInfo.Merge(m, src)
}
func (m *M2C_HeroInfo) XXX_Size() int {
	return xxx_messageInfo_M2C_HeroInfo.Size(m)
}
func (m *M2C_HeroInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_HeroInfo.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_HeroInfo proto.InternalMessageInfo

func (m *M2C_HeroInfo) GetInfo() *Hero {
	if m != nil {
		return m.Info
	}
	return nil
}

////////////////////////////////////////////////
// Equip
type C2M_QueryHeroEquips struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryHeroEquips) Reset()         { *m = C2M_QueryHeroEquips{} }
func (m *C2M_QueryHeroEquips) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryHeroEquips) ProtoMessage()    {}
func (*C2M_QueryHeroEquips) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{7}
}

func (m *C2M_QueryHeroEquips) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryHeroEquips.Unmarshal(m, b)
}
func (m *C2M_QueryHeroEquips) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryHeroEquips.Marshal(b, m, deterministic)
}
func (m *C2M_QueryHeroEquips) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryHeroEquips.Merge(m, src)
}
func (m *C2M_QueryHeroEquips) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryHeroEquips.Size(m)
}
func (m *C2M_QueryHeroEquips) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryHeroEquips.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryHeroEquips proto.InternalMessageInfo

func (m *C2M_QueryHeroEquips) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

type C2M_PutonEquip struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	EquipId              int64    `protobuf:"varint,2,opt,name=EquipId,proto3" json:"EquipId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_PutonEquip) Reset()         { *m = C2M_PutonEquip{} }
func (m *C2M_PutonEquip) String() string { return proto.CompactTextString(m) }
func (*C2M_PutonEquip) ProtoMessage()    {}
func (*C2M_PutonEquip) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{8}
}

func (m *C2M_PutonEquip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_PutonEquip.Unmarshal(m, b)
}
func (m *C2M_PutonEquip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_PutonEquip.Marshal(b, m, deterministic)
}
func (m *C2M_PutonEquip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_PutonEquip.Merge(m, src)
}
func (m *C2M_PutonEquip) XXX_Size() int {
	return xxx_messageInfo_C2M_PutonEquip.Size(m)
}
func (m *C2M_PutonEquip) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_PutonEquip.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_PutonEquip proto.InternalMessageInfo

func (m *C2M_PutonEquip) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *C2M_PutonEquip) GetEquipId() int64 {
	if m != nil {
		return m.EquipId
	}
	return 0
}

type C2M_TakeoffEquip struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	Pos                  int32    `protobuf:"varint,2,opt,name=Pos,proto3" json:"Pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_TakeoffEquip) Reset()         { *m = C2M_TakeoffEquip{} }
func (m *C2M_TakeoffEquip) String() string { return proto.CompactTextString(m) }
func (*C2M_TakeoffEquip) ProtoMessage()    {}
func (*C2M_TakeoffEquip) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{9}
}

func (m *C2M_TakeoffEquip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_TakeoffEquip.Unmarshal(m, b)
}
func (m *C2M_TakeoffEquip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_TakeoffEquip.Marshal(b, m, deterministic)
}
func (m *C2M_TakeoffEquip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_TakeoffEquip.Merge(m, src)
}
func (m *C2M_TakeoffEquip) XXX_Size() int {
	return xxx_messageInfo_C2M_TakeoffEquip.Size(m)
}
func (m *C2M_TakeoffEquip) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_TakeoffEquip.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_TakeoffEquip proto.InternalMessageInfo

func (m *C2M_TakeoffEquip) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *C2M_TakeoffEquip) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type M2C_HeroEquips struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	EquipIds             []int64  `protobuf:"varint,2,rep,packed,name=EquipIds,proto3" json:"EquipIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_HeroEquips) Reset()         { *m = M2C_HeroEquips{} }
func (m *M2C_HeroEquips) String() string { return proto.CompactTextString(m) }
func (*M2C_HeroEquips) ProtoMessage()    {}
func (*M2C_HeroEquips) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{10}
}

func (m *M2C_HeroEquips) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_HeroEquips.Unmarshal(m, b)
}
func (m *M2C_HeroEquips) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_HeroEquips.Marshal(b, m, deterministic)
}
func (m *M2C_HeroEquips) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_HeroEquips.Merge(m, src)
}
func (m *M2C_HeroEquips) XXX_Size() int {
	return xxx_messageInfo_M2C_HeroEquips.Size(m)
}
func (m *M2C_HeroEquips) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_HeroEquips.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_HeroEquips proto.InternalMessageInfo

func (m *M2C_HeroEquips) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *M2C_HeroEquips) GetEquipIds() []int64 {
	if m != nil {
		return m.EquipIds
	}
	return nil
}

////////////////////////////////////////////////
// Att
type M2C_HeroAttUpdate struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	AttValue             *Att     `protobuf:"bytes,2,opt,name=AttValue,proto3" json:"AttValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_HeroAttUpdate) Reset()         { *m = M2C_HeroAttUpdate{} }
func (m *M2C_HeroAttUpdate) String() string { return proto.CompactTextString(m) }
func (*M2C_HeroAttUpdate) ProtoMessage()    {}
func (*M2C_HeroAttUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1698784dfd4e5521, []int{11}
}

func (m *M2C_HeroAttUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_HeroAttUpdate.Unmarshal(m, b)
}
func (m *M2C_HeroAttUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_HeroAttUpdate.Marshal(b, m, deterministic)
}
func (m *M2C_HeroAttUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_HeroAttUpdate.Merge(m, src)
}
func (m *M2C_HeroAttUpdate) XXX_Size() int {
	return xxx_messageInfo_M2C_HeroAttUpdate.Size(m)
}
func (m *M2C_HeroAttUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_HeroAttUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_HeroAttUpdate proto.InternalMessageInfo

func (m *M2C_HeroAttUpdate) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *M2C_HeroAttUpdate) GetAttValue() *Att {
	if m != nil {
		return m.AttValue
	}
	return nil
}

func init() {
	proto.RegisterType((*Hero)(nil), "yokai_game.Hero")
	proto.RegisterType((*C2M_AddHero)(nil), "yokai_game.C2M_AddHero")
	proto.RegisterType((*C2M_DelHero)(nil), "yokai_game.C2M_DelHero")
	proto.RegisterType((*C2M_QueryHeros)(nil), "yokai_game.C2M_QueryHeros")
	proto.RegisterType((*M2C_HeroUpdate)(nil), "yokai_game.M2C_HeroUpdate")
	proto.RegisterType((*M2C_HeroList)(nil), "yokai_game.M2C_HeroList")
	proto.RegisterType((*M2C_HeroInfo)(nil), "yokai_game.M2C_HeroInfo")
	proto.RegisterType((*C2M_QueryHeroEquips)(nil), "yokai_game.C2M_QueryHeroEquips")
	proto.RegisterType((*C2M_PutonEquip)(nil), "yokai_game.C2M_PutonEquip")
	proto.RegisterType((*C2M_TakeoffEquip)(nil), "yokai_game.C2M_TakeoffEquip")
	proto.RegisterType((*M2C_HeroEquips)(nil), "yokai_game.M2C_HeroEquips")
	proto.RegisterType((*M2C_HeroAttUpdate)(nil), "yokai_game.M2C_HeroAttUpdate")
}

func init() { proto.RegisterFile("game/hero.proto", fileDescriptor_1698784dfd4e5521) }

var fileDescriptor_1698784dfd4e5521 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0x26, 0xdd, 0xe6, 0x3c, 0xa7, 0x92, 0x8b, 0xab, 0x48, 0x28, 0x0a, 0x61, 0x51, 0x29, 0xfe,
	0x48, 0x20, 0xca, 0x3d, 0xf9, 0x92, 0xbb, 0x16, 0x0c, 0xb4, 0x50, 0x43, 0x15, 0xf1, 0x25, 0xa4,
	0x66, 0xd3, 0x86, 0xfe, 0xd8, 0x98, 0x6c, 0x8a, 0xfd, 0xef, 0x65, 0x77, 0x93, 0xa6, 0x42, 0x5b,
	0xee, 0x29, 0xf3, 0xcd, 0x7c, 0xf3, 0xcd, 0xec, 0x37, 0x81, 0x9b, 0x45, 0xbc, 0xa1, 0xee, 0x92,
	0x16, 0xcc, 0xc9, 0x0b, 0xc6, 0x19, 0x86, 0x3d, 0x5b, 0xc5, 0x59, 0x24, 0xd2, 0x7d, 0x55, 0xcc,
	0x38, 0xdd, 0xa8, 0x62, 0xdf, 0x90, 0x89, 0x98, 0x73, 0x85, 0x09, 0x87, 0xee, 0x57, 0x5a, 0x30,
	0x6c, 0x40, 0x27, 0x48, 0x2c, 0xcd, 0xd6, 0x06, 0x28, 0xec, 0x04, 0x09, 0x7e, 0x01, 0x57, 0xb3,
	0x7d, 0x4e, 0x83, 0xc4, 0xea, 0xd8, 0xda, 0x40, 0x0f, 0x6b, 0x84, 0x4d, 0x40, 0xa3, 0xbf, 0xb9,
	0x85, 0x24, 0x51, 0x84, 0xf8, 0x39, 0xe8, 0x63, 0xba, 0xa3, 0x6b, 0xab, 0x2b, 0x89, 0x0a, 0xe0,
	0x97, 0xf0, 0x78, 0xf4, 0xa7, 0xca, 0xf2, 0x71, 0x56, 0x72, 0x4b, 0xb7, 0xd1, 0x00, 0x85, 0x6d,
	0x82, 0xbc, 0x81, 0xde, 0xbd, 0x37, 0x89, 0xfc, 0x24, 0x91, 0xc3, 0xdb, 0x61, 0xda, 0xf1, 0x30,
	0xf2, 0x4a, 0xd1, 0x86, 0x74, 0x7d, 0x6a, 0x47, 0x62, 0x82, 0x21, 0xca, 0xdf, 0x2a, 0x5a, 0xec,
	0x05, 0xa1, 0x24, 0xb7, 0x60, 0x4c, 0xbc, 0xfb, 0x48, 0x80, 0xef, 0x79, 0x12, 0x73, 0x8a, 0x5f,
	0x43, 0x37, 0xdb, 0xa6, 0x4c, 0x76, 0xf5, 0x3c, 0xd3, 0x69, 0xbd, 0x71, 0x04, 0x2b, 0x94, 0x55,
	0x72, 0x0b, 0x4f, 0x9a, 0x3e, 0xb1, 0x1f, 0x7e, 0x0b, 0xba, 0x30, 0xb4, 0xb4, 0x34, 0x1b, 0x9d,
	0x6c, 0x53, 0x65, 0xf2, 0xb9, 0xed, 0x0b, 0xb6, 0x29, 0x7b, 0xe0, 0xb4, 0x8f, 0xf0, 0xec, 0xbf,
	0xbd, 0xa5, 0x2f, 0xa5, 0x70, 0x41, 0x0a, 0x35, 0x4f, 0xac, 0x11, 0xb9, 0x53, 0xcf, 0x9c, 0x56,
	0x9c, 0x6d, 0x25, 0xf5, 0x1c, 0x13, 0x5b, 0xf0, 0x48, 0x12, 0xea, 0xab, 0xa1, 0xb0, 0x81, 0xe4,
	0x0b, 0x98, 0x42, 0x63, 0x16, 0xaf, 0x28, 0x4b, 0xd3, 0xcb, 0x2a, 0x26, 0xa0, 0x29, 0x2b, 0xeb,
	0xbb, 0x8b, 0x90, 0x0c, 0x5b, 0x5b, 0x2f, 0xef, 0x8a, 0xfb, 0x70, 0x5d, 0x8f, 0x14, 0x02, 0xe2,
	0xea, 0x07, 0x4c, 0x7e, 0xc2, 0xd3, 0x46, 0xc5, 0xe7, 0xbc, 0xbe, 0xcf, 0x39, 0xa1, 0xf7, 0x70,
	0xed, 0x73, 0xfe, 0x23, 0x5e, 0x57, 0x54, 0x6e, 0xd2, 0xf3, 0x6e, 0x8e, 0xdd, 0xf4, 0x39, 0x0f,
	0x0f, 0x84, 0xbb, 0x0f, 0xbf, 0xde, 0x2d, 0x32, 0xbe, 0xac, 0xe6, 0xce, 0x6f, 0xb6, 0x71, 0x25,
	0x2d, 0x63, 0xea, 0x1b, 0x95, 0xb4, 0xd8, 0xd1, 0xc2, 0x95, 0x7f, 0xbb, 0x2b, 0x7a, 0xe7, 0x57,
	0x32, 0xfe, 0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x3f, 0x1a, 0x3a, 0x39, 0x03, 0x00, 0x00,
}
