// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/item.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// Item
type Item struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TypeId               int32    `protobuf:"varint,2,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Item) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type C2M_AddItem struct {
	TypeId               int32    `protobuf:"varint,1,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_AddItem) Reset()         { *m = C2M_AddItem{} }
func (m *C2M_AddItem) String() string { return proto.CompactTextString(m) }
func (*C2M_AddItem) ProtoMessage()    {}
func (*C2M_AddItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{1}
}

func (m *C2M_AddItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_AddItem.Unmarshal(m, b)
}
func (m *C2M_AddItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_AddItem.Marshal(b, m, deterministic)
}
func (m *C2M_AddItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_AddItem.Merge(m, src)
}
func (m *C2M_AddItem) XXX_Size() int {
	return xxx_messageInfo_C2M_AddItem.Size(m)
}
func (m *C2M_AddItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_AddItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_AddItem proto.InternalMessageInfo

func (m *C2M_AddItem) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type C2M_DelItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_DelItem) Reset()         { *m = C2M_DelItem{} }
func (m *C2M_DelItem) String() string { return proto.CompactTextString(m) }
func (*C2M_DelItem) ProtoMessage()    {}
func (*C2M_DelItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{2}
}

func (m *C2M_DelItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_DelItem.Unmarshal(m, b)
}
func (m *C2M_DelItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_DelItem.Marshal(b, m, deterministic)
}
func (m *C2M_DelItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_DelItem.Merge(m, src)
}
func (m *C2M_DelItem) XXX_Size() int {
	return xxx_messageInfo_C2M_DelItem.Size(m)
}
func (m *C2M_DelItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_DelItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_DelItem proto.InternalMessageInfo

func (m *C2M_DelItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type C2M_UseItem struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_UseItem) Reset()         { *m = C2M_UseItem{} }
func (m *C2M_UseItem) String() string { return proto.CompactTextString(m) }
func (*C2M_UseItem) ProtoMessage()    {}
func (*C2M_UseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{3}
}

func (m *C2M_UseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_UseItem.Unmarshal(m, b)
}
func (m *C2M_UseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_UseItem.Marshal(b, m, deterministic)
}
func (m *C2M_UseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_UseItem.Merge(m, src)
}
func (m *C2M_UseItem) XXX_Size() int {
	return xxx_messageInfo_C2M_UseItem.Size(m)
}
func (m *C2M_UseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_UseItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_UseItem proto.InternalMessageInfo

func (m *C2M_UseItem) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type C2M_QueryItems struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryItems) Reset()         { *m = C2M_QueryItems{} }
func (m *C2M_QueryItems) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryItems) ProtoMessage()    {}
func (*C2M_QueryItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{4}
}

func (m *C2M_QueryItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryItems.Unmarshal(m, b)
}
func (m *C2M_QueryItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryItems.Marshal(b, m, deterministic)
}
func (m *C2M_QueryItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryItems.Merge(m, src)
}
func (m *C2M_QueryItems) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryItems.Size(m)
}
func (m *C2M_QueryItems) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryItems.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryItems proto.InternalMessageInfo

type M2C_ItemList struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ItemList) Reset()         { *m = M2C_ItemList{} }
func (m *M2C_ItemList) String() string { return proto.CompactTextString(m) }
func (*M2C_ItemList) ProtoMessage()    {}
func (*M2C_ItemList) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{5}
}

func (m *M2C_ItemList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ItemList.Unmarshal(m, b)
}
func (m *M2C_ItemList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ItemList.Marshal(b, m, deterministic)
}
func (m *M2C_ItemList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ItemList.Merge(m, src)
}
func (m *M2C_ItemList) XXX_Size() int {
	return xxx_messageInfo_M2C_ItemList.Size(m)
}
func (m *M2C_ItemList) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ItemList.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ItemList proto.InternalMessageInfo

func (m *M2C_ItemList) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type M2C_ItemUpdate struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ItemUpdate) Reset()         { *m = M2C_ItemUpdate{} }
func (m *M2C_ItemUpdate) String() string { return proto.CompactTextString(m) }
func (*M2C_ItemUpdate) ProtoMessage()    {}
func (*M2C_ItemUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{6}
}

func (m *M2C_ItemUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ItemUpdate.Unmarshal(m, b)
}
func (m *M2C_ItemUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ItemUpdate.Marshal(b, m, deterministic)
}
func (m *M2C_ItemUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ItemUpdate.Merge(m, src)
}
func (m *M2C_ItemUpdate) XXX_Size() int {
	return xxx_messageInfo_M2C_ItemUpdate.Size(m)
}
func (m *M2C_ItemUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ItemUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ItemUpdate proto.InternalMessageInfo

func (m *M2C_ItemUpdate) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type M2C_DelItem struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_DelItem) Reset()         { *m = M2C_DelItem{} }
func (m *M2C_DelItem) String() string { return proto.CompactTextString(m) }
func (*M2C_DelItem) ProtoMessage()    {}
func (*M2C_DelItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{7}
}

func (m *M2C_DelItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_DelItem.Unmarshal(m, b)
}
func (m *M2C_DelItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_DelItem.Marshal(b, m, deterministic)
}
func (m *M2C_DelItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_DelItem.Merge(m, src)
}
func (m *M2C_DelItem) XXX_Size() int {
	return xxx_messageInfo_M2C_DelItem.Size(m)
}
func (m *M2C_DelItem) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_DelItem.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_DelItem proto.InternalMessageInfo

func (m *M2C_DelItem) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

////////////////////////////////////////////////
// Equip
type C2M_QueryHeroEquips struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryHeroEquips) Reset()         { *m = C2M_QueryHeroEquips{} }
func (m *C2M_QueryHeroEquips) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryHeroEquips) ProtoMessage()    {}
func (*C2M_QueryHeroEquips) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{8}
}

func (m *C2M_QueryHeroEquips) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryHeroEquips.Unmarshal(m, b)
}
func (m *C2M_QueryHeroEquips) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryHeroEquips.Marshal(b, m, deterministic)
}
func (m *C2M_QueryHeroEquips) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryHeroEquips.Merge(m, src)
}
func (m *C2M_QueryHeroEquips) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryHeroEquips.Size(m)
}
func (m *C2M_QueryHeroEquips) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryHeroEquips.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryHeroEquips proto.InternalMessageInfo

func (m *C2M_QueryHeroEquips) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

type C2M_PutonEquip struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	EquipId              int64    `protobuf:"varint,2,opt,name=EquipId,proto3" json:"EquipId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_PutonEquip) Reset()         { *m = C2M_PutonEquip{} }
func (m *C2M_PutonEquip) String() string { return proto.CompactTextString(m) }
func (*C2M_PutonEquip) ProtoMessage()    {}
func (*C2M_PutonEquip) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{9}
}

func (m *C2M_PutonEquip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_PutonEquip.Unmarshal(m, b)
}
func (m *C2M_PutonEquip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_PutonEquip.Marshal(b, m, deterministic)
}
func (m *C2M_PutonEquip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_PutonEquip.Merge(m, src)
}
func (m *C2M_PutonEquip) XXX_Size() int {
	return xxx_messageInfo_C2M_PutonEquip.Size(m)
}
func (m *C2M_PutonEquip) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_PutonEquip.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_PutonEquip proto.InternalMessageInfo

func (m *C2M_PutonEquip) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *C2M_PutonEquip) GetEquipId() int64 {
	if m != nil {
		return m.EquipId
	}
	return 0
}

type C2M_TakeoffEquip struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	Pos                  int32    `protobuf:"varint,2,opt,name=Pos,proto3" json:"Pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_TakeoffEquip) Reset()         { *m = C2M_TakeoffEquip{} }
func (m *C2M_TakeoffEquip) String() string { return proto.CompactTextString(m) }
func (*C2M_TakeoffEquip) ProtoMessage()    {}
func (*C2M_TakeoffEquip) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{10}
}

func (m *C2M_TakeoffEquip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_TakeoffEquip.Unmarshal(m, b)
}
func (m *C2M_TakeoffEquip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_TakeoffEquip.Marshal(b, m, deterministic)
}
func (m *C2M_TakeoffEquip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_TakeoffEquip.Merge(m, src)
}
func (m *C2M_TakeoffEquip) XXX_Size() int {
	return xxx_messageInfo_C2M_TakeoffEquip.Size(m)
}
func (m *C2M_TakeoffEquip) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_TakeoffEquip.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_TakeoffEquip proto.InternalMessageInfo

func (m *C2M_TakeoffEquip) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *C2M_TakeoffEquip) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type M2C_HeroEquips struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	Equips               []*Item  `protobuf:"bytes,2,rep,name=Equips,proto3" json:"Equips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_HeroEquips) Reset()         { *m = M2C_HeroEquips{} }
func (m *M2C_HeroEquips) String() string { return proto.CompactTextString(m) }
func (*M2C_HeroEquips) ProtoMessage()    {}
func (*M2C_HeroEquips) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{11}
}

func (m *M2C_HeroEquips) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_HeroEquips.Unmarshal(m, b)
}
func (m *M2C_HeroEquips) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_HeroEquips.Marshal(b, m, deterministic)
}
func (m *M2C_HeroEquips) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_HeroEquips.Merge(m, src)
}
func (m *M2C_HeroEquips) XXX_Size() int {
	return xxx_messageInfo_M2C_HeroEquips.Size(m)
}
func (m *M2C_HeroEquips) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_HeroEquips.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_HeroEquips proto.InternalMessageInfo

func (m *M2C_HeroEquips) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *M2C_HeroEquips) GetEquips() []*Item {
	if m != nil {
		return m.Equips
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "yokai_game.Item")
	proto.RegisterType((*C2M_AddItem)(nil), "yokai_game.C2M_AddItem")
	proto.RegisterType((*C2M_DelItem)(nil), "yokai_game.C2M_DelItem")
	proto.RegisterType((*C2M_UseItem)(nil), "yokai_game.C2M_UseItem")
	proto.RegisterType((*C2M_QueryItems)(nil), "yokai_game.C2M_QueryItems")
	proto.RegisterType((*M2C_ItemList)(nil), "yokai_game.M2C_ItemList")
	proto.RegisterType((*M2C_ItemUpdate)(nil), "yokai_game.M2C_ItemUpdate")
	proto.RegisterType((*M2C_DelItem)(nil), "yokai_game.M2C_DelItem")
	proto.RegisterType((*C2M_QueryHeroEquips)(nil), "yokai_game.C2M_QueryHeroEquips")
	proto.RegisterType((*C2M_PutonEquip)(nil), "yokai_game.C2M_PutonEquip")
	proto.RegisterType((*C2M_TakeoffEquip)(nil), "yokai_game.C2M_TakeoffEquip")
	proto.RegisterType((*M2C_HeroEquips)(nil), "yokai_game.M2C_HeroEquips")
}

func init() { proto.RegisterFile("game/item.proto", fileDescriptor_20b3be662c2ee0bd) }

var fileDescriptor_20b3be662c2ee0bd = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4b, 0xeb, 0x40,
	0x10, 0xc6, 0x49, 0xd2, 0xf6, 0xc1, 0xf4, 0x51, 0xc3, 0x0a, 0x92, 0x8b, 0x50, 0x16, 0x95, 0x20,
	0x9a, 0x40, 0x85, 0x9e, 0x3c, 0x68, 0xab, 0x60, 0xc0, 0x4a, 0x0d, 0xed, 0xc5, 0x4b, 0x48, 0xcd,
	0xb6, 0x86, 0x1a, 0x37, 0x66, 0x37, 0x42, 0xff, 0x7b, 0x99, 0xdd, 0xa4, 0xf5, 0xd0, 0xe8, 0x29,
	0xf3, 0xcd, 0xfc, 0xbe, 0xd9, 0x99, 0xdd, 0xc0, 0xc1, 0x2a, 0xce, 0x98, 0x9f, 0x4a, 0x96, 0x79,
	0x79, 0xc1, 0x25, 0x27, 0xb0, 0xe1, 0xeb, 0x38, 0x8d, 0x30, 0x4d, 0x6f, 0xa0, 0x15, 0x48, 0x96,
	0x91, 0x1e, 0x98, 0x41, 0xe2, 0x18, 0x7d, 0xc3, 0xb5, 0x42, 0x33, 0x48, 0xc8, 0x11, 0x74, 0x66,
	0x9b, 0x9c, 0x05, 0x89, 0x63, 0xf6, 0x0d, 0xb7, 0x1d, 0x56, 0x8a, 0xd8, 0x60, 0x3d, 0x95, 0x99,
	0x63, 0xa9, 0x24, 0x86, 0xf4, 0x14, 0xba, 0xe3, 0xc1, 0x24, 0xba, 0x4d, 0x12, 0xd5, 0x68, 0x67,
	0x34, 0x7e, 0x1a, 0xe9, 0xb1, 0xc6, 0xee, 0xd8, 0xfb, 0xbe, 0xf3, 0xea, 0x2e, 0x73, 0xc1, 0xea,
	0x2e, 0xf8, 0xdd, 0x22, 0x95, 0xa2, 0x36, 0xf4, 0x10, 0x7b, 0x2e, 0x59, 0xb1, 0xc1, 0x94, 0xa0,
	0x43, 0xf8, 0x3f, 0x19, 0x8c, 0x23, 0x14, 0x8f, 0xa9, 0x90, 0xe4, 0x0c, 0xda, 0xb8, 0xaa, 0x70,
	0x8c, 0xbe, 0xe5, 0x76, 0x07, 0xb6, 0xb7, 0x5b, 0xd6, 0x43, 0x28, 0xd4, 0x65, 0x3a, 0x84, 0x5e,
	0xed, 0x9b, 0xe7, 0x49, 0x2c, 0x19, 0x39, 0x81, 0x16, 0x96, 0xd4, 0x89, 0xfb, 0x8c, 0xaa, 0x8a,
	0x83, 0xa2, 0xaf, 0xde, 0xa3, 0x69, 0xd0, 0x4b, 0x38, 0xdc, 0x0e, 0xfa, 0xc0, 0x0a, 0x7e, 0xff,
	0x59, 0xa6, 0xb9, 0x40, 0x1c, 0xd5, 0x0e, 0xd7, 0x8a, 0x8e, 0xf4, 0x5e, 0xd3, 0x52, 0xf2, 0x0f,
	0x85, 0x36, 0x91, 0xc4, 0x81, 0x7f, 0x0a, 0xa8, 0x5e, 0xc6, 0x0a, 0x6b, 0x49, 0xaf, 0xc1, 0xc6,
	0x1e, 0xb3, 0x78, 0xcd, 0xf8, 0x72, 0xf9, 0x7b, 0x17, 0x1b, 0xac, 0x29, 0x17, 0xd5, 0xdb, 0x62,
	0x48, 0x43, 0x7d, 0x1f, 0x7f, 0xcf, 0x4a, 0x5c, 0xe8, 0x68, 0xc2, 0x31, 0x1b, 0xae, 0xb8, 0xaa,
	0x8f, 0x2e, 0x5e, 0xce, 0x57, 0xa9, 0x7c, 0x2b, 0x17, 0xde, 0x2b, 0xcf, 0x7c, 0x45, 0xa5, 0x5c,
	0x7f, 0x23, 0xc1, 0x8a, 0x2f, 0x56, 0xf8, 0xea, 0x8f, 0xf4, 0xd1, 0xba, 0xe8, 0xa8, 0xf8, 0xea,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x8c, 0x3f, 0xbb, 0xb0, 0x02, 0x00, 0x00,
}
