// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/item.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// Item
type Item struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TypeId               int32    `protobuf:"varint,2,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Item) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type C2M_AddItem struct {
	TypeId               int32    `protobuf:"varint,1,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_AddItem) Reset()         { *m = C2M_AddItem{} }
func (m *C2M_AddItem) String() string { return proto.CompactTextString(m) }
func (*C2M_AddItem) ProtoMessage()    {}
func (*C2M_AddItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{1}
}

func (m *C2M_AddItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_AddItem.Unmarshal(m, b)
}
func (m *C2M_AddItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_AddItem.Marshal(b, m, deterministic)
}
func (m *C2M_AddItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_AddItem.Merge(m, src)
}
func (m *C2M_AddItem) XXX_Size() int {
	return xxx_messageInfo_C2M_AddItem.Size(m)
}
func (m *C2M_AddItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_AddItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_AddItem proto.InternalMessageInfo

func (m *C2M_AddItem) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type C2M_DelItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_DelItem) Reset()         { *m = C2M_DelItem{} }
func (m *C2M_DelItem) String() string { return proto.CompactTextString(m) }
func (*C2M_DelItem) ProtoMessage()    {}
func (*C2M_DelItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{2}
}

func (m *C2M_DelItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_DelItem.Unmarshal(m, b)
}
func (m *C2M_DelItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_DelItem.Marshal(b, m, deterministic)
}
func (m *C2M_DelItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_DelItem.Merge(m, src)
}
func (m *C2M_DelItem) XXX_Size() int {
	return xxx_messageInfo_C2M_DelItem.Size(m)
}
func (m *C2M_DelItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_DelItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_DelItem proto.InternalMessageInfo

func (m *C2M_DelItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type C2M_UseItem struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_UseItem) Reset()         { *m = C2M_UseItem{} }
func (m *C2M_UseItem) String() string { return proto.CompactTextString(m) }
func (*C2M_UseItem) ProtoMessage()    {}
func (*C2M_UseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{3}
}

func (m *C2M_UseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_UseItem.Unmarshal(m, b)
}
func (m *C2M_UseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_UseItem.Marshal(b, m, deterministic)
}
func (m *C2M_UseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_UseItem.Merge(m, src)
}
func (m *C2M_UseItem) XXX_Size() int {
	return xxx_messageInfo_C2M_UseItem.Size(m)
}
func (m *C2M_UseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_UseItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_UseItem proto.InternalMessageInfo

func (m *C2M_UseItem) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type C2M_QueryItems struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryItems) Reset()         { *m = C2M_QueryItems{} }
func (m *C2M_QueryItems) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryItems) ProtoMessage()    {}
func (*C2M_QueryItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{4}
}

func (m *C2M_QueryItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryItems.Unmarshal(m, b)
}
func (m *C2M_QueryItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryItems.Marshal(b, m, deterministic)
}
func (m *C2M_QueryItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryItems.Merge(m, src)
}
func (m *C2M_QueryItems) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryItems.Size(m)
}
func (m *C2M_QueryItems) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryItems.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryItems proto.InternalMessageInfo

type M2C_ItemList struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ItemList) Reset()         { *m = M2C_ItemList{} }
func (m *M2C_ItemList) String() string { return proto.CompactTextString(m) }
func (*M2C_ItemList) ProtoMessage()    {}
func (*M2C_ItemList) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{5}
}

func (m *M2C_ItemList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ItemList.Unmarshal(m, b)
}
func (m *M2C_ItemList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ItemList.Marshal(b, m, deterministic)
}
func (m *M2C_ItemList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ItemList.Merge(m, src)
}
func (m *M2C_ItemList) XXX_Size() int {
	return xxx_messageInfo_M2C_ItemList.Size(m)
}
func (m *M2C_ItemList) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ItemList.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ItemList proto.InternalMessageInfo

func (m *M2C_ItemList) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type M2C_ItemUpdate struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ItemUpdate) Reset()         { *m = M2C_ItemUpdate{} }
func (m *M2C_ItemUpdate) String() string { return proto.CompactTextString(m) }
func (*M2C_ItemUpdate) ProtoMessage()    {}
func (*M2C_ItemUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{6}
}

func (m *M2C_ItemUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ItemUpdate.Unmarshal(m, b)
}
func (m *M2C_ItemUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ItemUpdate.Marshal(b, m, deterministic)
}
func (m *M2C_ItemUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ItemUpdate.Merge(m, src)
}
func (m *M2C_ItemUpdate) XXX_Size() int {
	return xxx_messageInfo_M2C_ItemUpdate.Size(m)
}
func (m *M2C_ItemUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ItemUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ItemUpdate proto.InternalMessageInfo

func (m *M2C_ItemUpdate) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type M2C_DelItem struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_DelItem) Reset()         { *m = M2C_DelItem{} }
func (m *M2C_DelItem) String() string { return proto.CompactTextString(m) }
func (*M2C_DelItem) ProtoMessage()    {}
func (*M2C_DelItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b3be662c2ee0bd, []int{7}
}

func (m *M2C_DelItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_DelItem.Unmarshal(m, b)
}
func (m *M2C_DelItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_DelItem.Marshal(b, m, deterministic)
}
func (m *M2C_DelItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_DelItem.Merge(m, src)
}
func (m *M2C_DelItem) XXX_Size() int {
	return xxx_messageInfo_M2C_DelItem.Size(m)
}
func (m *M2C_DelItem) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_DelItem.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_DelItem proto.InternalMessageInfo

func (m *M2C_DelItem) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "yokai_game.Item")
	proto.RegisterType((*C2M_AddItem)(nil), "yokai_game.C2M_AddItem")
	proto.RegisterType((*C2M_DelItem)(nil), "yokai_game.C2M_DelItem")
	proto.RegisterType((*C2M_UseItem)(nil), "yokai_game.C2M_UseItem")
	proto.RegisterType((*C2M_QueryItems)(nil), "yokai_game.C2M_QueryItems")
	proto.RegisterType((*M2C_ItemList)(nil), "yokai_game.M2C_ItemList")
	proto.RegisterType((*M2C_ItemUpdate)(nil), "yokai_game.M2C_ItemUpdate")
	proto.RegisterType((*M2C_DelItem)(nil), "yokai_game.M2C_DelItem")
}

func init() { proto.RegisterFile("game/item.proto", fileDescriptor_20b3be662c2ee0bd) }

var fileDescriptor_20b3be662c2ee0bd = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0xdb, 0xc3, 0x54, 0x62, 0xd8, 0x83, 0xe4, 0x22, 0x84, 0x45, 0x25, 0x88, 0x24,
	0x10, 0xa1, 0x67, 0xb5, 0x5e, 0x02, 0x56, 0x30, 0xd8, 0x8b, 0x97, 0x90, 0xba, 0x43, 0x5d, 0x74,
	0xd9, 0x90, 0xdd, 0x08, 0xf9, 0xf7, 0x32, 0x9b, 0xc6, 0x7a, 0xa8, 0xa7, 0x9d, 0x99, 0xf7, 0x31,
	0xf3, 0x58, 0x38, 0xdd, 0xd5, 0x0a, 0x33, 0x69, 0x51, 0xa5, 0x4d, 0xab, 0xad, 0x66, 0xd0, 0xeb,
	0xcf, 0x5a, 0x56, 0x34, 0xe6, 0x77, 0x30, 0x2d, 0x2c, 0x2a, 0x16, 0xc0, 0xa4, 0x10, 0x91, 0x17,
	0x7b, 0x89, 0x5f, 0x4e, 0x0a, 0xc1, 0xce, 0x60, 0xfe, 0xda, 0x37, 0x58, 0x88, 0x68, 0x12, 0x7b,
	0xc9, 0xac, 0xdc, 0x77, 0x2c, 0x04, 0xff, 0xb9, 0x53, 0x91, 0xef, 0x86, 0x54, 0xf2, 0x4b, 0x58,
	0xac, 0xf2, 0x75, 0x75, 0x2f, 0x84, 0x33, 0x3a, 0x08, 0xbd, 0xbf, 0x42, 0x7e, 0x3e, 0xd0, 0x1e,
	0xf1, 0xeb, 0xd8, 0xbe, 0xd1, 0x65, 0x63, 0x70, 0x74, 0xa1, 0xf7, 0x97, 0xb2, 0xef, 0x78, 0x08,
	0x01, 0xd1, 0x5e, 0x3a, 0x6c, 0x7b, 0x1a, 0x19, 0xbe, 0x84, 0x93, 0x75, 0xbe, 0xaa, 0xa8, 0x79,
	0x92, 0xc6, 0xb2, 0x2b, 0x98, 0x51, 0x54, 0x13, 0x79, 0xb1, 0x9f, 0x2c, 0xf2, 0x30, 0x3d, 0x84,
	0x4d, 0x89, 0x54, 0x0e, 0x30, 0x5f, 0x42, 0x30, 0xea, 0x36, 0x8d, 0xa8, 0x2d, 0xb2, 0x0b, 0x98,
	0x12, 0xe4, 0x36, 0x1e, 0x13, 0x3a, 0x94, 0x0e, 0x25, 0xdd, 0x98, 0xe3, 0x9f, 0x43, 0x1f, 0x6e,
	0xde, 0xae, 0x77, 0xd2, 0x7e, 0x74, 0xdb, 0xf4, 0x5d, 0xab, 0xcc, 0x59, 0x49, 0x3d, 0xbc, 0x95,
	0xc1, 0xf6, 0x1b, 0xdb, 0xcc, 0x7d, 0x46, 0x46, 0xfe, 0xdb, 0xb9, 0xab, 0x6f, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x17, 0xc6, 0xa5, 0x20, 0xab, 0x01, 0x00, 0x00,
}
