// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/player.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// player
type LitePlayer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Exp                  int64    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LitePlayer) Reset()         { *m = LitePlayer{} }
func (m *LitePlayer) String() string { return proto.CompactTextString(m) }
func (*LitePlayer) ProtoMessage()    {}
func (*LitePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{0}
}

func (m *LitePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LitePlayer.Unmarshal(m, b)
}
func (m *LitePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LitePlayer.Marshal(b, m, deterministic)
}
func (m *LitePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LitePlayer.Merge(m, src)
}
func (m *LitePlayer) XXX_Size() int {
	return xxx_messageInfo_LitePlayer.Size(m)
}
func (m *LitePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_LitePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_LitePlayer proto.InternalMessageInfo

func (m *LitePlayer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LitePlayer) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *LitePlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LitePlayer) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *LitePlayer) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type PlayerInfo struct {
	LiteInfo             *LitePlayer `protobuf:"bytes,1,opt,name=lite_info,json=liteInfo,proto3" json:"lite_info,omitempty"`
	HeroNums             int32       `protobuf:"varint,2,opt,name=hero_nums,json=heroNums,proto3" json:"hero_nums,omitempty"`
	ItemNums             int32       `protobuf:"varint,3,opt,name=item_nums,json=itemNums,proto3" json:"item_nums,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{1}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetLiteInfo() *LitePlayer {
	if m != nil {
		return m.LiteInfo
	}
	return nil
}

func (m *PlayerInfo) GetHeroNums() int32 {
	if m != nil {
		return m.HeroNums
	}
	return 0
}

func (m *PlayerInfo) GetItemNums() int32 {
	if m != nil {
		return m.ItemNums
	}
	return 0
}

type C2M_CreatePlayer struct {
	RpcId                int32    `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_CreatePlayer) Reset()         { *m = C2M_CreatePlayer{} }
func (m *C2M_CreatePlayer) String() string { return proto.CompactTextString(m) }
func (*C2M_CreatePlayer) ProtoMessage()    {}
func (*C2M_CreatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{2}
}

func (m *C2M_CreatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_CreatePlayer.Unmarshal(m, b)
}
func (m *C2M_CreatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_CreatePlayer.Marshal(b, m, deterministic)
}
func (m *C2M_CreatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_CreatePlayer.Merge(m, src)
}
func (m *C2M_CreatePlayer) XXX_Size() int {
	return xxx_messageInfo_C2M_CreatePlayer.Size(m)
}
func (m *C2M_CreatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_CreatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_CreatePlayer proto.InternalMessageInfo

func (m *C2M_CreatePlayer) GetRpcId() int32 {
	if m != nil {
		return m.RpcId
	}
	return 0
}

func (m *C2M_CreatePlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type M2C_CreatePlayer struct {
	RpcId                int32       `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error                int32       `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message              string      `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *M2C_CreatePlayer) Reset()         { *m = M2C_CreatePlayer{} }
func (m *M2C_CreatePlayer) String() string { return proto.CompactTextString(m) }
func (*M2C_CreatePlayer) ProtoMessage()    {}
func (*M2C_CreatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{3}
}

func (m *M2C_CreatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_CreatePlayer.Unmarshal(m, b)
}
func (m *M2C_CreatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_CreatePlayer.Marshal(b, m, deterministic)
}
func (m *M2C_CreatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_CreatePlayer.Merge(m, src)
}
func (m *M2C_CreatePlayer) XXX_Size() int {
	return xxx_messageInfo_M2C_CreatePlayer.Size(m)
}
func (m *M2C_CreatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_CreatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_CreatePlayer proto.InternalMessageInfo

func (m *M2C_CreatePlayer) GetRpcId() int32 {
	if m != nil {
		return m.RpcId
	}
	return 0
}

func (m *M2C_CreatePlayer) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *M2C_CreatePlayer) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *M2C_CreatePlayer) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MC_SelectPlayer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_SelectPlayer) Reset()         { *m = MC_SelectPlayer{} }
func (m *MC_SelectPlayer) String() string { return proto.CompactTextString(m) }
func (*MC_SelectPlayer) ProtoMessage()    {}
func (*MC_SelectPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{4}
}

func (m *MC_SelectPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_SelectPlayer.Unmarshal(m, b)
}
func (m *MC_SelectPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_SelectPlayer.Marshal(b, m, deterministic)
}
func (m *MC_SelectPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_SelectPlayer.Merge(m, src)
}
func (m *MC_SelectPlayer) XXX_Size() int {
	return xxx_messageInfo_MC_SelectPlayer.Size(m)
}
func (m *MC_SelectPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_SelectPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MC_SelectPlayer proto.InternalMessageInfo

func (m *MC_SelectPlayer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MS_SelectPlayer struct {
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	ErrorCode            int32       `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MS_SelectPlayer) Reset()         { *m = MS_SelectPlayer{} }
func (m *MS_SelectPlayer) String() string { return proto.CompactTextString(m) }
func (*MS_SelectPlayer) ProtoMessage()    {}
func (*MS_SelectPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{5}
}

func (m *MS_SelectPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_SelectPlayer.Unmarshal(m, b)
}
func (m *MS_SelectPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_SelectPlayer.Marshal(b, m, deterministic)
}
func (m *MS_SelectPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_SelectPlayer.Merge(m, src)
}
func (m *MS_SelectPlayer) XXX_Size() int {
	return xxx_messageInfo_MS_SelectPlayer.Size(m)
}
func (m *MS_SelectPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_SelectPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MS_SelectPlayer proto.InternalMessageInfo

func (m *MS_SelectPlayer) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MS_SelectPlayer) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type MC_ExpirePlayer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_ExpirePlayer) Reset()         { *m = MC_ExpirePlayer{} }
func (m *MC_ExpirePlayer) String() string { return proto.CompactTextString(m) }
func (*MC_ExpirePlayer) ProtoMessage()    {}
func (*MC_ExpirePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{6}
}

func (m *MC_ExpirePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_ExpirePlayer.Unmarshal(m, b)
}
func (m *MC_ExpirePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_ExpirePlayer.Marshal(b, m, deterministic)
}
func (m *MC_ExpirePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_ExpirePlayer.Merge(m, src)
}
func (m *MC_ExpirePlayer) XXX_Size() int {
	return xxx_messageInfo_MC_ExpirePlayer.Size(m)
}
func (m *MC_ExpirePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_ExpirePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MC_ExpirePlayer proto.InternalMessageInfo

type C2M_QueryPlayerInfo struct {
	RpcId                int32    `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryPlayerInfo) Reset()         { *m = C2M_QueryPlayerInfo{} }
func (m *C2M_QueryPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryPlayerInfo) ProtoMessage()    {}
func (*C2M_QueryPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{7}
}

func (m *C2M_QueryPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryPlayerInfo.Unmarshal(m, b)
}
func (m *C2M_QueryPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryPlayerInfo.Marshal(b, m, deterministic)
}
func (m *C2M_QueryPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryPlayerInfo.Merge(m, src)
}
func (m *C2M_QueryPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryPlayerInfo.Size(m)
}
func (m *C2M_QueryPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryPlayerInfo proto.InternalMessageInfo

func (m *C2M_QueryPlayerInfo) GetRpcId() int32 {
	if m != nil {
		return m.RpcId
	}
	return 0
}

type M2C_QueryPlayerInfo struct {
	RpcId                int32       `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error                int32       `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message              string      `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *M2C_QueryPlayerInfo) Reset()         { *m = M2C_QueryPlayerInfo{} }
func (m *M2C_QueryPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*M2C_QueryPlayerInfo) ProtoMessage()    {}
func (*M2C_QueryPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{8}
}

func (m *M2C_QueryPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_QueryPlayerInfo.Unmarshal(m, b)
}
func (m *M2C_QueryPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_QueryPlayerInfo.Marshal(b, m, deterministic)
}
func (m *M2C_QueryPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_QueryPlayerInfo.Merge(m, src)
}
func (m *M2C_QueryPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_M2C_QueryPlayerInfo.Size(m)
}
func (m *M2C_QueryPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_QueryPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_QueryPlayerInfo proto.InternalMessageInfo

func (m *M2C_QueryPlayerInfo) GetRpcId() int32 {
	if m != nil {
		return m.RpcId
	}
	return 0
}

func (m *M2C_QueryPlayerInfo) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *M2C_QueryPlayerInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *M2C_QueryPlayerInfo) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MC_ChangeExp struct {
	AddExp               int64    `protobuf:"varint,1,opt,name=add_exp,json=addExp,proto3" json:"add_exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_ChangeExp) Reset()         { *m = MC_ChangeExp{} }
func (m *MC_ChangeExp) String() string { return proto.CompactTextString(m) }
func (*MC_ChangeExp) ProtoMessage()    {}
func (*MC_ChangeExp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{9}
}

func (m *MC_ChangeExp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_ChangeExp.Unmarshal(m, b)
}
func (m *MC_ChangeExp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_ChangeExp.Marshal(b, m, deterministic)
}
func (m *MC_ChangeExp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_ChangeExp.Merge(m, src)
}
func (m *MC_ChangeExp) XXX_Size() int {
	return xxx_messageInfo_MC_ChangeExp.Size(m)
}
func (m *MC_ChangeExp) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_ChangeExp.DiscardUnknown(m)
}

var xxx_messageInfo_MC_ChangeExp proto.InternalMessageInfo

func (m *MC_ChangeExp) GetAddExp() int64 {
	if m != nil {
		return m.AddExp
	}
	return 0
}

type MS_ExpUpdate struct {
	Exp                  int64    `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MS_ExpUpdate) Reset()         { *m = MS_ExpUpdate{} }
func (m *MS_ExpUpdate) String() string { return proto.CompactTextString(m) }
func (*MS_ExpUpdate) ProtoMessage()    {}
func (*MS_ExpUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{10}
}

func (m *MS_ExpUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_ExpUpdate.Unmarshal(m, b)
}
func (m *MS_ExpUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_ExpUpdate.Marshal(b, m, deterministic)
}
func (m *MS_ExpUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_ExpUpdate.Merge(m, src)
}
func (m *MS_ExpUpdate) XXX_Size() int {
	return xxx_messageInfo_MS_ExpUpdate.Size(m)
}
func (m *MS_ExpUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_ExpUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MS_ExpUpdate proto.InternalMessageInfo

func (m *MS_ExpUpdate) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

type MC_ChangeLevel struct {
	AddLevel             int32    `protobuf:"varint,1,opt,name=add_level,json=addLevel,proto3" json:"add_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_ChangeLevel) Reset()         { *m = MC_ChangeLevel{} }
func (m *MC_ChangeLevel) String() string { return proto.CompactTextString(m) }
func (*MC_ChangeLevel) ProtoMessage()    {}
func (*MC_ChangeLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{11}
}

func (m *MC_ChangeLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_ChangeLevel.Unmarshal(m, b)
}
func (m *MC_ChangeLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_ChangeLevel.Marshal(b, m, deterministic)
}
func (m *MC_ChangeLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_ChangeLevel.Merge(m, src)
}
func (m *MC_ChangeLevel) XXX_Size() int {
	return xxx_messageInfo_MC_ChangeLevel.Size(m)
}
func (m *MC_ChangeLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_ChangeLevel.DiscardUnknown(m)
}

var xxx_messageInfo_MC_ChangeLevel proto.InternalMessageInfo

func (m *MC_ChangeLevel) GetAddLevel() int32 {
	if m != nil {
		return m.AddLevel
	}
	return 0
}

type MS_LevelUpdate struct {
	Level                int32    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MS_LevelUpdate) Reset()         { *m = MS_LevelUpdate{} }
func (m *MS_LevelUpdate) String() string { return proto.CompactTextString(m) }
func (*MS_LevelUpdate) ProtoMessage()    {}
func (*MS_LevelUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{12}
}

func (m *MS_LevelUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_LevelUpdate.Unmarshal(m, b)
}
func (m *MS_LevelUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_LevelUpdate.Marshal(b, m, deterministic)
}
func (m *MS_LevelUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_LevelUpdate.Merge(m, src)
}
func (m *MS_LevelUpdate) XXX_Size() int {
	return xxx_messageInfo_MS_LevelUpdate.Size(m)
}
func (m *MS_LevelUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_LevelUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MS_LevelUpdate proto.InternalMessageInfo

func (m *MS_LevelUpdate) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func init() {
	proto.RegisterType((*LitePlayer)(nil), "yokai_game.LitePlayer")
	proto.RegisterType((*PlayerInfo)(nil), "yokai_game.PlayerInfo")
	proto.RegisterType((*C2M_CreatePlayer)(nil), "yokai_game.C2M_CreatePlayer")
	proto.RegisterType((*M2C_CreatePlayer)(nil), "yokai_game.M2C_CreatePlayer")
	proto.RegisterType((*MC_SelectPlayer)(nil), "yokai_game.MC_SelectPlayer")
	proto.RegisterType((*MS_SelectPlayer)(nil), "yokai_game.MS_SelectPlayer")
	proto.RegisterType((*MC_ExpirePlayer)(nil), "yokai_game.MC_ExpirePlayer")
	proto.RegisterType((*C2M_QueryPlayerInfo)(nil), "yokai_game.C2M_QueryPlayerInfo")
	proto.RegisterType((*M2C_QueryPlayerInfo)(nil), "yokai_game.M2C_QueryPlayerInfo")
	proto.RegisterType((*MC_ChangeExp)(nil), "yokai_game.MC_ChangeExp")
	proto.RegisterType((*MS_ExpUpdate)(nil), "yokai_game.MS_ExpUpdate")
	proto.RegisterType((*MC_ChangeLevel)(nil), "yokai_game.MC_ChangeLevel")
	proto.RegisterType((*MS_LevelUpdate)(nil), "yokai_game.MS_LevelUpdate")
}

func init() { proto.RegisterFile("game/player.proto", fileDescriptor_e574b74a3b2962cb) }

var fileDescriptor_e574b74a3b2962cb = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x41, 0x6b, 0xdb, 0x4c,
	0x10, 0x65, 0x6d, 0x2b, 0x89, 0xe7, 0x0b, 0x8e, 0xb3, 0x31, 0x5f, 0x05, 0xa5, 0xe0, 0xee, 0xa1,
	0x35, 0x69, 0x6b, 0x83, 0x73, 0xed, 0xa9, 0xc2, 0x07, 0x43, 0x54, 0x5a, 0x99, 0x5e, 0xd2, 0xc0,
	0xb2, 0xd1, 0x4e, 0xec, 0xa5, 0x96, 0x56, 0xac, 0xa4, 0xd4, 0xa6, 0xd7, 0x42, 0xff, 0x76, 0xd9,
	0x5d, 0x57, 0x4e, 0x21, 0x85, 0xf4, 0xd0, 0x93, 0x66, 0xe6, 0x8d, 0x66, 0x67, 0xde, 0xbc, 0x81,
	0xd3, 0xa5, 0xc8, 0x70, 0x52, 0xac, 0xc5, 0x16, 0xcd, 0xb8, 0x30, 0xba, 0xd2, 0x14, 0xb6, 0xfa,
	0x8b, 0x50, 0xdc, 0x02, 0xec, 0x2b, 0xc0, 0xa5, 0xaa, 0xf0, 0x83, 0xc3, 0x69, 0x0f, 0x5a, 0x4a,
	0x86, 0x64, 0x48, 0x46, 0xed, 0xa4, 0xa5, 0x24, 0x7d, 0x06, 0x20, 0xd2, 0x54, 0xd7, 0x79, 0xc5,
	0x95, 0x0c, 0x5b, 0x2e, 0xde, 0xdd, 0x45, 0xe6, 0x92, 0x52, 0xe8, 0xe4, 0x22, 0xc3, 0xb0, 0x3d,
	0x24, 0xa3, 0x6e, 0xe2, 0x6c, 0xda, 0x87, 0x36, 0x6e, 0x8a, 0xb0, 0xe3, 0x72, 0xad, 0x49, 0x07,
	0x10, 0xac, 0xf1, 0x0e, 0xd7, 0x61, 0x30, 0x24, 0xa3, 0x20, 0xf1, 0x0e, 0xfb, 0x06, 0xe0, 0x1f,
	0x9d, 0xe7, 0xb7, 0x9a, 0x5e, 0x40, 0x77, 0xad, 0x2a, 0xe4, 0x2a, 0xbf, 0xd5, 0xee, 0xfd, 0xff,
	0xa6, 0xff, 0x8f, 0xf7, 0x6d, 0x8e, 0xf7, 0x3d, 0x26, 0x47, 0x36, 0xd1, 0xfd, 0xf4, 0x14, 0xba,
	0x2b, 0x34, 0x9a, 0xe7, 0x75, 0x56, 0xba, 0xe6, 0x82, 0xe4, 0xc8, 0x06, 0xde, 0xd7, 0x59, 0x69,
	0x41, 0x55, 0x61, 0xe6, 0xc1, 0xb6, 0x07, 0x6d, 0xc0, 0x82, 0xec, 0x2d, 0xf4, 0xa3, 0x69, 0xcc,
	0x23, 0x83, 0xa2, 0x99, 0x7d, 0x00, 0x41, 0x52, 0xa4, 0x73, 0x19, 0x5e, 0xf9, 0x36, 0x9d, 0xd3,
	0x8c, 0x48, 0xf6, 0x23, 0xb2, 0xef, 0x04, 0xfa, 0xf1, 0x34, 0x7a, 0xcc, 0xef, 0x03, 0x08, 0x66,
	0xc6, 0x68, 0x13, 0x7e, 0xf6, 0x51, 0xe7, 0xd0, 0x10, 0x0e, 0x63, 0x2c, 0x4b, 0xb1, 0xc4, 0xf0,
	0xda, 0xd5, 0xfd, 0xe5, 0xd2, 0x73, 0xe8, 0xfc, 0x89, 0x82, 0x3d, 0x5b, 0x89, 0xcb, 0x61, 0xcf,
	0xe1, 0x24, 0x8e, 0xf8, 0x02, 0xd7, 0x98, 0x56, 0x0f, 0xef, 0x8f, 0x5d, 0xc3, 0x49, 0xbc, 0xf8,
	0x3d, 0xe5, 0x2f, 0x5e, 0xb0, 0xeb, 0x47, 0xdb, 0x30, 0x4f, 0xb5, 0xc4, 0x1d, 0xc3, 0x5d, 0x17,
	0x89, 0xb4, 0x44, 0x76, 0xea, 0x1a, 0x98, 0x6d, 0x0a, 0x65, 0x76, 0x2c, 0xb0, 0x57, 0x70, 0x66,
	0x89, 0xfd, 0x58, 0xa3, 0xd9, 0xde, 0x5b, 0xef, 0x83, 0xe4, 0xb0, 0x1f, 0x04, 0xce, 0x2c, 0x8f,
	0x8f, 0xca, 0xfe, 0xa7, 0x54, 0xbe, 0x84, 0xe3, 0x38, 0xe2, 0xd1, 0x4a, 0xe4, 0x4b, 0x9c, 0x6d,
	0x0a, 0xfa, 0x04, 0x0e, 0x85, 0x94, 0xdc, 0x0a, 0xd9, 0x93, 0x79, 0x20, 0xa4, 0x9c, 0x6d, 0x0a,
	0x36, 0x84, 0xe3, 0x78, 0x61, 0x47, 0xfe, 0x54, 0x48, 0x51, 0x35, 0x6a, 0x27, 0x8d, 0xda, 0xd9,
	0x1b, 0xe8, 0x35, 0xa5, 0x2e, 0xad, 0xd2, 0xad, 0x12, 0x6d, 0x31, 0x7f, 0x03, 0xc4, 0x2b, 0x51,
	0x48, 0xe9, 0x40, 0xf6, 0x02, 0x7a, 0xf1, 0x82, 0x3b, 0x7b, 0x57, 0xb2, 0x39, 0x17, 0x72, 0xef,
	0x5c, 0xde, 0xbd, 0xbe, 0x3a, 0x5f, 0xaa, 0x6a, 0x55, 0xdf, 0x8c, 0x53, 0x9d, 0x4d, 0xdc, 0x2c,
	0x4a, 0xfb, 0x2f, 0x2f, 0xd1, 0xdc, 0xa1, 0x99, 0xb8, 0xe3, 0x9e, 0xd8, 0x01, 0x6f, 0x0e, 0x9c,
	0x7d, 0xf1, 0x33, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xe0, 0x41, 0x5b, 0xfd, 0x03, 0x00, 0x00,
}
