// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/player.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// player
type LitePlayer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Exp                  int64    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LitePlayer) Reset()         { *m = LitePlayer{} }
func (m *LitePlayer) String() string { return proto.CompactTextString(m) }
func (*LitePlayer) ProtoMessage()    {}
func (*LitePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{0}
}

func (m *LitePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LitePlayer.Unmarshal(m, b)
}
func (m *LitePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LitePlayer.Marshal(b, m, deterministic)
}
func (m *LitePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LitePlayer.Merge(m, src)
}
func (m *LitePlayer) XXX_Size() int {
	return xxx_messageInfo_LitePlayer.Size(m)
}
func (m *LitePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_LitePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_LitePlayer proto.InternalMessageInfo

func (m *LitePlayer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LitePlayer) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *LitePlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LitePlayer) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *LitePlayer) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type PlayerInfo struct {
	LiteInfo             *LitePlayer `protobuf:"bytes,1,opt,name=lite_info,json=liteInfo,proto3" json:"lite_info,omitempty"`
	HeroNums             int32       `protobuf:"varint,2,opt,name=hero_nums,json=heroNums,proto3" json:"hero_nums,omitempty"`
	ItemNums             int32       `protobuf:"varint,3,opt,name=item_nums,json=itemNums,proto3" json:"item_nums,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{1}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetLiteInfo() *LitePlayer {
	if m != nil {
		return m.LiteInfo
	}
	return nil
}

func (m *PlayerInfo) GetHeroNums() int32 {
	if m != nil {
		return m.HeroNums
	}
	return 0
}

func (m *PlayerInfo) GetItemNums() int32 {
	if m != nil {
		return m.ItemNums
	}
	return 0
}

type C2M_CreatePlayer struct {
	RpcId                int32    `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_CreatePlayer) Reset()         { *m = C2M_CreatePlayer{} }
func (m *C2M_CreatePlayer) String() string { return proto.CompactTextString(m) }
func (*C2M_CreatePlayer) ProtoMessage()    {}
func (*C2M_CreatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{2}
}

func (m *C2M_CreatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_CreatePlayer.Unmarshal(m, b)
}
func (m *C2M_CreatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_CreatePlayer.Marshal(b, m, deterministic)
}
func (m *C2M_CreatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_CreatePlayer.Merge(m, src)
}
func (m *C2M_CreatePlayer) XXX_Size() int {
	return xxx_messageInfo_C2M_CreatePlayer.Size(m)
}
func (m *C2M_CreatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_CreatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_CreatePlayer proto.InternalMessageInfo

func (m *C2M_CreatePlayer) GetRpcId() int32 {
	if m != nil {
		return m.RpcId
	}
	return 0
}

func (m *C2M_CreatePlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type M2C_CreatePlayer struct {
	RpcId                int32       `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error                int32       `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message              string      `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *M2C_CreatePlayer) Reset()         { *m = M2C_CreatePlayer{} }
func (m *M2C_CreatePlayer) String() string { return proto.CompactTextString(m) }
func (*M2C_CreatePlayer) ProtoMessage()    {}
func (*M2C_CreatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{3}
}

func (m *M2C_CreatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_CreatePlayer.Unmarshal(m, b)
}
func (m *M2C_CreatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_CreatePlayer.Marshal(b, m, deterministic)
}
func (m *M2C_CreatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_CreatePlayer.Merge(m, src)
}
func (m *M2C_CreatePlayer) XXX_Size() int {
	return xxx_messageInfo_M2C_CreatePlayer.Size(m)
}
func (m *M2C_CreatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_CreatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_CreatePlayer proto.InternalMessageInfo

func (m *M2C_CreatePlayer) GetRpcId() int32 {
	if m != nil {
		return m.RpcId
	}
	return 0
}

func (m *M2C_CreatePlayer) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *M2C_CreatePlayer) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *M2C_CreatePlayer) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MC_SelectPlayer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_SelectPlayer) Reset()         { *m = MC_SelectPlayer{} }
func (m *MC_SelectPlayer) String() string { return proto.CompactTextString(m) }
func (*MC_SelectPlayer) ProtoMessage()    {}
func (*MC_SelectPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{4}
}

func (m *MC_SelectPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_SelectPlayer.Unmarshal(m, b)
}
func (m *MC_SelectPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_SelectPlayer.Marshal(b, m, deterministic)
}
func (m *MC_SelectPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_SelectPlayer.Merge(m, src)
}
func (m *MC_SelectPlayer) XXX_Size() int {
	return xxx_messageInfo_MC_SelectPlayer.Size(m)
}
func (m *MC_SelectPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_SelectPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MC_SelectPlayer proto.InternalMessageInfo

func (m *MC_SelectPlayer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MS_SelectPlayer struct {
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	ErrorCode            int32       `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MS_SelectPlayer) Reset()         { *m = MS_SelectPlayer{} }
func (m *MS_SelectPlayer) String() string { return proto.CompactTextString(m) }
func (*MS_SelectPlayer) ProtoMessage()    {}
func (*MS_SelectPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{5}
}

func (m *MS_SelectPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_SelectPlayer.Unmarshal(m, b)
}
func (m *MS_SelectPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_SelectPlayer.Marshal(b, m, deterministic)
}
func (m *MS_SelectPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_SelectPlayer.Merge(m, src)
}
func (m *MS_SelectPlayer) XXX_Size() int {
	return xxx_messageInfo_MS_SelectPlayer.Size(m)
}
func (m *MS_SelectPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_SelectPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MS_SelectPlayer proto.InternalMessageInfo

func (m *MS_SelectPlayer) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MS_SelectPlayer) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type C2M_QueryPlayerInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryPlayerInfo) Reset()         { *m = C2M_QueryPlayerInfo{} }
func (m *C2M_QueryPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryPlayerInfo) ProtoMessage()    {}
func (*C2M_QueryPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{6}
}

func (m *C2M_QueryPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryPlayerInfo.Unmarshal(m, b)
}
func (m *C2M_QueryPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryPlayerInfo.Marshal(b, m, deterministic)
}
func (m *C2M_QueryPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryPlayerInfo.Merge(m, src)
}
func (m *C2M_QueryPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryPlayerInfo.Size(m)
}
func (m *C2M_QueryPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryPlayerInfo proto.InternalMessageInfo

type M2C_QueryPlayerInfo struct {
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error                int32       `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *M2C_QueryPlayerInfo) Reset()         { *m = M2C_QueryPlayerInfo{} }
func (m *M2C_QueryPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*M2C_QueryPlayerInfo) ProtoMessage()    {}
func (*M2C_QueryPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{7}
}

func (m *M2C_QueryPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_QueryPlayerInfo.Unmarshal(m, b)
}
func (m *M2C_QueryPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_QueryPlayerInfo.Marshal(b, m, deterministic)
}
func (m *M2C_QueryPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_QueryPlayerInfo.Merge(m, src)
}
func (m *M2C_QueryPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_M2C_QueryPlayerInfo.Size(m)
}
func (m *M2C_QueryPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_QueryPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_QueryPlayerInfo proto.InternalMessageInfo

func (m *M2C_QueryPlayerInfo) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *M2C_QueryPlayerInfo) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type C2M_ChangeExp struct {
	AddExp               int64    `protobuf:"varint,1,opt,name=AddExp,proto3" json:"AddExp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ChangeExp) Reset()         { *m = C2M_ChangeExp{} }
func (m *C2M_ChangeExp) String() string { return proto.CompactTextString(m) }
func (*C2M_ChangeExp) ProtoMessage()    {}
func (*C2M_ChangeExp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{8}
}

func (m *C2M_ChangeExp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ChangeExp.Unmarshal(m, b)
}
func (m *C2M_ChangeExp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ChangeExp.Marshal(b, m, deterministic)
}
func (m *C2M_ChangeExp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ChangeExp.Merge(m, src)
}
func (m *C2M_ChangeExp) XXX_Size() int {
	return xxx_messageInfo_C2M_ChangeExp.Size(m)
}
func (m *C2M_ChangeExp) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ChangeExp.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ChangeExp proto.InternalMessageInfo

func (m *C2M_ChangeExp) GetAddExp() int64 {
	if m != nil {
		return m.AddExp
	}
	return 0
}

type M2C_ExpUpdate struct {
	Exp                  int64    `protobuf:"varint,1,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ExpUpdate) Reset()         { *m = M2C_ExpUpdate{} }
func (m *M2C_ExpUpdate) String() string { return proto.CompactTextString(m) }
func (*M2C_ExpUpdate) ProtoMessage()    {}
func (*M2C_ExpUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{9}
}

func (m *M2C_ExpUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ExpUpdate.Unmarshal(m, b)
}
func (m *M2C_ExpUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ExpUpdate.Marshal(b, m, deterministic)
}
func (m *M2C_ExpUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ExpUpdate.Merge(m, src)
}
func (m *M2C_ExpUpdate) XXX_Size() int {
	return xxx_messageInfo_M2C_ExpUpdate.Size(m)
}
func (m *M2C_ExpUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ExpUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ExpUpdate proto.InternalMessageInfo

func (m *M2C_ExpUpdate) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *M2C_ExpUpdate) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type C2M_ChangeLevel struct {
	AddLevel             int32    `protobuf:"varint,1,opt,name=AddLevel,proto3" json:"AddLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ChangeLevel) Reset()         { *m = C2M_ChangeLevel{} }
func (m *C2M_ChangeLevel) String() string { return proto.CompactTextString(m) }
func (*C2M_ChangeLevel) ProtoMessage()    {}
func (*C2M_ChangeLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{10}
}

func (m *C2M_ChangeLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ChangeLevel.Unmarshal(m, b)
}
func (m *C2M_ChangeLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ChangeLevel.Marshal(b, m, deterministic)
}
func (m *C2M_ChangeLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ChangeLevel.Merge(m, src)
}
func (m *C2M_ChangeLevel) XXX_Size() int {
	return xxx_messageInfo_C2M_ChangeLevel.Size(m)
}
func (m *C2M_ChangeLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ChangeLevel.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ChangeLevel proto.InternalMessageInfo

func (m *C2M_ChangeLevel) GetAddLevel() int32 {
	if m != nil {
		return m.AddLevel
	}
	return 0
}

type C2M_SyncPlayerInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_SyncPlayerInfo) Reset()         { *m = C2M_SyncPlayerInfo{} }
func (m *C2M_SyncPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*C2M_SyncPlayerInfo) ProtoMessage()    {}
func (*C2M_SyncPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{11}
}

func (m *C2M_SyncPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_SyncPlayerInfo.Unmarshal(m, b)
}
func (m *C2M_SyncPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_SyncPlayerInfo.Marshal(b, m, deterministic)
}
func (m *C2M_SyncPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_SyncPlayerInfo.Merge(m, src)
}
func (m *C2M_SyncPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_C2M_SyncPlayerInfo.Size(m)
}
func (m *C2M_SyncPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_SyncPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_SyncPlayerInfo proto.InternalMessageInfo

type C2M_PublicSyncPlayerInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_PublicSyncPlayerInfo) Reset()         { *m = C2M_PublicSyncPlayerInfo{} }
func (m *C2M_PublicSyncPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*C2M_PublicSyncPlayerInfo) ProtoMessage()    {}
func (*C2M_PublicSyncPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{12}
}

func (m *C2M_PublicSyncPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_PublicSyncPlayerInfo.Unmarshal(m, b)
}
func (m *C2M_PublicSyncPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_PublicSyncPlayerInfo.Marshal(b, m, deterministic)
}
func (m *C2M_PublicSyncPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_PublicSyncPlayerInfo.Merge(m, src)
}
func (m *C2M_PublicSyncPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_C2M_PublicSyncPlayerInfo.Size(m)
}
func (m *C2M_PublicSyncPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_PublicSyncPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_PublicSyncPlayerInfo proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LitePlayer)(nil), "yokai_game.LitePlayer")
	proto.RegisterType((*PlayerInfo)(nil), "yokai_game.PlayerInfo")
	proto.RegisterType((*C2M_CreatePlayer)(nil), "yokai_game.C2M_CreatePlayer")
	proto.RegisterType((*M2C_CreatePlayer)(nil), "yokai_game.M2C_CreatePlayer")
	proto.RegisterType((*MC_SelectPlayer)(nil), "yokai_game.MC_SelectPlayer")
	proto.RegisterType((*MS_SelectPlayer)(nil), "yokai_game.MS_SelectPlayer")
	proto.RegisterType((*C2M_QueryPlayerInfo)(nil), "yokai_game.C2M_QueryPlayerInfo")
	proto.RegisterType((*M2C_QueryPlayerInfo)(nil), "yokai_game.M2C_QueryPlayerInfo")
	proto.RegisterType((*C2M_ChangeExp)(nil), "yokai_game.C2M_ChangeExp")
	proto.RegisterType((*M2C_ExpUpdate)(nil), "yokai_game.M2C_ExpUpdate")
	proto.RegisterType((*C2M_ChangeLevel)(nil), "yokai_game.C2M_ChangeLevel")
	proto.RegisterType((*C2M_SyncPlayerInfo)(nil), "yokai_game.C2M_SyncPlayerInfo")
	proto.RegisterType((*C2M_PublicSyncPlayerInfo)(nil), "yokai_game.C2M_PublicSyncPlayerInfo")
}

func init() { proto.RegisterFile("game/player.proto", fileDescriptor_e574b74a3b2962cb) }

var fileDescriptor_e574b74a3b2962cb = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x45, 0xb6, 0x95, 0xda, 0x53, 0x52, 0xbb, 0x1b, 0x37, 0x2c, 0x29, 0x05, 0x77, 0x2f, 0x35,
	0xa1, 0xb5, 0xc1, 0x39, 0xf4, 0xd2, 0x4b, 0x6a, 0x7c, 0x30, 0xc4, 0x25, 0x95, 0x29, 0x85, 0x34,
	0x20, 0x64, 0xed, 0xc4, 0x5e, 0x2a, 0x69, 0xc5, 0x4a, 0x4a, 0x6d, 0x7a, 0xed, 0x87, 0x97, 0x1d,
	0x29, 0x56, 0x52, 0x5a, 0x68, 0x4e, 0x9e, 0x79, 0xef, 0xad, 0xdf, 0xcc, 0xdb, 0x15, 0x3c, 0x5f,
	0x07, 0x31, 0x8e, 0xd3, 0x28, 0xd8, 0xa1, 0x19, 0xa5, 0x46, 0xe7, 0x9a, 0xc1, 0x4e, 0x7f, 0x0f,
	0x94, 0x6f, 0x09, 0xf1, 0x03, 0xe0, 0x42, 0xe5, 0x78, 0x49, 0x3c, 0x7b, 0x06, 0x0d, 0x25, 0xb9,
	0x33, 0x70, 0x86, 0x4d, 0xaf, 0xa1, 0x24, 0x7b, 0x05, 0x10, 0x84, 0xa1, 0x2e, 0x92, 0xdc, 0x57,
	0x92, 0x37, 0x08, 0xef, 0x54, 0xc8, 0x5c, 0x32, 0x06, 0xad, 0x24, 0x88, 0x91, 0x37, 0x07, 0xce,
	0xb0, 0xe3, 0x51, 0xcd, 0x7a, 0xd0, 0xc4, 0x6d, 0xca, 0x5b, 0xa4, 0xb5, 0x25, 0xeb, 0x83, 0x1b,
	0xe1, 0x2d, 0x46, 0xdc, 0x1d, 0x38, 0x43, 0xd7, 0x2b, 0x1b, 0xf1, 0x13, 0xa0, 0x34, 0x9d, 0x27,
	0x37, 0x9a, 0x9d, 0x41, 0x27, 0x52, 0x39, 0xfa, 0x2a, 0xb9, 0xd1, 0xe4, 0xff, 0x74, 0x72, 0x3c,
	0xaa, 0xc7, 0x1c, 0xd5, 0x33, 0x7a, 0x6d, 0x2b, 0xa4, 0x43, 0x2f, 0xa1, 0xb3, 0x41, 0xa3, 0xfd,
	0xa4, 0x88, 0x33, 0x1a, 0xce, 0xf5, 0xda, 0x16, 0xf8, 0x54, 0xc4, 0x99, 0x25, 0x55, 0x8e, 0x71,
	0x49, 0x36, 0x4b, 0xd2, 0x02, 0x96, 0x14, 0x1f, 0xa0, 0x37, 0x9d, 0x2c, 0xfc, 0xa9, 0xc1, 0x60,
	0xbf, 0x7b, 0x1f, 0x5c, 0x2f, 0x0d, 0xe7, 0x92, 0x5f, 0x95, 0x63, 0x52, 0xb3, 0x5f, 0xd1, 0xa9,
	0x57, 0x14, 0xbf, 0x1c, 0xe8, 0x2d, 0x26, 0xd3, 0xff, 0x39, 0xde, 0x07, 0x77, 0x66, 0x8c, 0x36,
	0xfc, 0x5b, 0x89, 0x52, 0xc3, 0x38, 0x3c, 0x59, 0x60, 0x96, 0x05, 0x6b, 0xe4, 0xd7, 0xf4, 0xbf,
	0x77, 0x2d, 0x3b, 0x85, 0xd6, 0xbf, 0x22, 0xa8, 0xd3, 0xf2, 0x48, 0x23, 0x5e, 0x43, 0x77, 0x31,
	0xf5, 0x97, 0x18, 0x61, 0x98, 0xff, 0xfd, 0xfe, 0xc4, 0x35, 0x74, 0x17, 0xcb, 0x87, 0x92, 0x47,
	0x38, 0xd8, 0xeb, 0x47, 0x3b, 0xb0, 0x1f, 0x6a, 0x89, 0x55, 0xc2, 0x1d, 0x42, 0xa6, 0x5a, 0xa2,
	0x78, 0x01, 0x47, 0x36, 0xc5, 0xcf, 0x05, 0x9a, 0x5d, 0x7d, 0x56, 0x7c, 0x85, 0x23, 0x9b, 0xce,
	0x1f, 0xf0, 0xa3, 0x8c, 0xf7, 0xb1, 0x35, 0xee, 0xc5, 0x26, 0xde, 0xc0, 0x21, 0xdd, 0xda, 0x26,
	0x48, 0xd6, 0x38, 0xdb, 0xa6, 0xec, 0x18, 0x0e, 0xce, 0xa5, 0x9c, 0x6d, 0xd3, 0x6a, 0xe5, 0xaa,
	0x13, 0xef, 0xe1, 0xd0, 0x4e, 0x30, 0xdb, 0xa6, 0x5f, 0x52, 0x19, 0xe4, 0xf4, 0x28, 0x6b, 0x95,
	0x2d, 0xad, 0xc3, 0x05, 0x3d, 0xca, 0xca, 0x81, 0x1a, 0xf1, 0x0e, 0xba, 0xb5, 0x03, 0x41, 0xec,
	0x04, 0xda, 0xe7, 0x52, 0x96, 0x5a, 0xa7, 0x7c, 0x46, 0x77, 0xbd, 0xe8, 0x03, 0xb3, 0xf2, 0xe5,
	0x2e, 0x09, 0xef, 0xed, 0x7f, 0x02, 0xdc, 0xa2, 0x97, 0xc5, 0x2a, 0x52, 0xe1, 0x43, 0xee, 0xe3,
	0xdb, 0xab, 0xd3, 0xb5, 0xca, 0x37, 0xc5, 0x6a, 0x14, 0xea, 0x78, 0x4c, 0x11, 0x28, 0x5d, 0xfe,
	0xfa, 0x19, 0x9a, 0x5b, 0x34, 0x63, 0xfa, 0x46, 0xc7, 0x36, 0x97, 0xd5, 0x01, 0xd5, 0x67, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x28, 0x87, 0xa1, 0xc0, 0xc4, 0x03, 0x00, 0x00,
}
