// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/player.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// player
type PlayerInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exp                  int64    `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	HeroNums             int32    `protobuf:"varint,5,opt,name=hero_nums,json=heroNums,proto3" json:"hero_nums,omitempty"`
	ItemNums             int32    `protobuf:"varint,6,opt,name=item_nums,json=itemNums,proto3" json:"item_nums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{0}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerInfo) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *PlayerInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *PlayerInfo) GetHeroNums() int32 {
	if m != nil {
		return m.HeroNums
	}
	return 0
}

func (m *PlayerInfo) GetItemNums() int32 {
	if m != nil {
		return m.ItemNums
	}
	return 0
}

type MC_CreatePlayer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_CreatePlayer) Reset()         { *m = MC_CreatePlayer{} }
func (m *MC_CreatePlayer) String() string { return proto.CompactTextString(m) }
func (*MC_CreatePlayer) ProtoMessage()    {}
func (*MC_CreatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{1}
}

func (m *MC_CreatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_CreatePlayer.Unmarshal(m, b)
}
func (m *MC_CreatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_CreatePlayer.Marshal(b, m, deterministic)
}
func (m *MC_CreatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_CreatePlayer.Merge(m, src)
}
func (m *MC_CreatePlayer) XXX_Size() int {
	return xxx_messageInfo_MC_CreatePlayer.Size(m)
}
func (m *MC_CreatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_CreatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MC_CreatePlayer proto.InternalMessageInfo

func (m *MC_CreatePlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MS_CreatePlayer struct {
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	ErrorCode            int32       `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MS_CreatePlayer) Reset()         { *m = MS_CreatePlayer{} }
func (m *MS_CreatePlayer) String() string { return proto.CompactTextString(m) }
func (*MS_CreatePlayer) ProtoMessage()    {}
func (*MS_CreatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{2}
}

func (m *MS_CreatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_CreatePlayer.Unmarshal(m, b)
}
func (m *MS_CreatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_CreatePlayer.Marshal(b, m, deterministic)
}
func (m *MS_CreatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_CreatePlayer.Merge(m, src)
}
func (m *MS_CreatePlayer) XXX_Size() int {
	return xxx_messageInfo_MS_CreatePlayer.Size(m)
}
func (m *MS_CreatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_CreatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MS_CreatePlayer proto.InternalMessageInfo

func (m *MS_CreatePlayer) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MS_CreatePlayer) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type MC_SelectPlayer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_SelectPlayer) Reset()         { *m = MC_SelectPlayer{} }
func (m *MC_SelectPlayer) String() string { return proto.CompactTextString(m) }
func (*MC_SelectPlayer) ProtoMessage()    {}
func (*MC_SelectPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{3}
}

func (m *MC_SelectPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_SelectPlayer.Unmarshal(m, b)
}
func (m *MC_SelectPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_SelectPlayer.Marshal(b, m, deterministic)
}
func (m *MC_SelectPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_SelectPlayer.Merge(m, src)
}
func (m *MC_SelectPlayer) XXX_Size() int {
	return xxx_messageInfo_MC_SelectPlayer.Size(m)
}
func (m *MC_SelectPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_SelectPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MC_SelectPlayer proto.InternalMessageInfo

func (m *MC_SelectPlayer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MS_SelectPlayer struct {
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	ErrorCode            int32       `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MS_SelectPlayer) Reset()         { *m = MS_SelectPlayer{} }
func (m *MS_SelectPlayer) String() string { return proto.CompactTextString(m) }
func (*MS_SelectPlayer) ProtoMessage()    {}
func (*MS_SelectPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{4}
}

func (m *MS_SelectPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_SelectPlayer.Unmarshal(m, b)
}
func (m *MS_SelectPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_SelectPlayer.Marshal(b, m, deterministic)
}
func (m *MS_SelectPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_SelectPlayer.Merge(m, src)
}
func (m *MS_SelectPlayer) XXX_Size() int {
	return xxx_messageInfo_MS_SelectPlayer.Size(m)
}
func (m *MS_SelectPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_SelectPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MS_SelectPlayer proto.InternalMessageInfo

func (m *MS_SelectPlayer) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MS_SelectPlayer) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type MC_ExpirePlayer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_ExpirePlayer) Reset()         { *m = MC_ExpirePlayer{} }
func (m *MC_ExpirePlayer) String() string { return proto.CompactTextString(m) }
func (*MC_ExpirePlayer) ProtoMessage()    {}
func (*MC_ExpirePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{5}
}

func (m *MC_ExpirePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_ExpirePlayer.Unmarshal(m, b)
}
func (m *MC_ExpirePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_ExpirePlayer.Marshal(b, m, deterministic)
}
func (m *MC_ExpirePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_ExpirePlayer.Merge(m, src)
}
func (m *MC_ExpirePlayer) XXX_Size() int {
	return xxx_messageInfo_MC_ExpirePlayer.Size(m)
}
func (m *MC_ExpirePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_ExpirePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MC_ExpirePlayer proto.InternalMessageInfo

type MC_QueryPlayerInfos struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_QueryPlayerInfos) Reset()         { *m = MC_QueryPlayerInfos{} }
func (m *MC_QueryPlayerInfos) String() string { return proto.CompactTextString(m) }
func (*MC_QueryPlayerInfos) ProtoMessage()    {}
func (*MC_QueryPlayerInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{6}
}

func (m *MC_QueryPlayerInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_QueryPlayerInfos.Unmarshal(m, b)
}
func (m *MC_QueryPlayerInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_QueryPlayerInfos.Marshal(b, m, deterministic)
}
func (m *MC_QueryPlayerInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_QueryPlayerInfos.Merge(m, src)
}
func (m *MC_QueryPlayerInfos) XXX_Size() int {
	return xxx_messageInfo_MC_QueryPlayerInfos.Size(m)
}
func (m *MC_QueryPlayerInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_QueryPlayerInfos.DiscardUnknown(m)
}

var xxx_messageInfo_MC_QueryPlayerInfos proto.InternalMessageInfo

type MS_QueryPlayerInfo struct {
	Info                 *PlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MS_QueryPlayerInfo) Reset()         { *m = MS_QueryPlayerInfo{} }
func (m *MS_QueryPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MS_QueryPlayerInfo) ProtoMessage()    {}
func (*MS_QueryPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{7}
}

func (m *MS_QueryPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_QueryPlayerInfo.Unmarshal(m, b)
}
func (m *MS_QueryPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_QueryPlayerInfo.Marshal(b, m, deterministic)
}
func (m *MS_QueryPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_QueryPlayerInfo.Merge(m, src)
}
func (m *MS_QueryPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MS_QueryPlayerInfo.Size(m)
}
func (m *MS_QueryPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_QueryPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MS_QueryPlayerInfo proto.InternalMessageInfo

func (m *MS_QueryPlayerInfo) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MS_QueryPlayerInfos struct {
	Infos                []*PlayerInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MS_QueryPlayerInfos) Reset()         { *m = MS_QueryPlayerInfos{} }
func (m *MS_QueryPlayerInfos) String() string { return proto.CompactTextString(m) }
func (*MS_QueryPlayerInfos) ProtoMessage()    {}
func (*MS_QueryPlayerInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{8}
}

func (m *MS_QueryPlayerInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_QueryPlayerInfos.Unmarshal(m, b)
}
func (m *MS_QueryPlayerInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_QueryPlayerInfos.Marshal(b, m, deterministic)
}
func (m *MS_QueryPlayerInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_QueryPlayerInfos.Merge(m, src)
}
func (m *MS_QueryPlayerInfos) XXX_Size() int {
	return xxx_messageInfo_MS_QueryPlayerInfos.Size(m)
}
func (m *MS_QueryPlayerInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_QueryPlayerInfos.DiscardUnknown(m)
}

var xxx_messageInfo_MS_QueryPlayerInfos proto.InternalMessageInfo

func (m *MS_QueryPlayerInfos) GetInfos() []*PlayerInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type MC_ChangeExp struct {
	AddExp               int64    `protobuf:"varint,1,opt,name=add_exp,json=addExp,proto3" json:"add_exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_ChangeExp) Reset()         { *m = MC_ChangeExp{} }
func (m *MC_ChangeExp) String() string { return proto.CompactTextString(m) }
func (*MC_ChangeExp) ProtoMessage()    {}
func (*MC_ChangeExp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{9}
}

func (m *MC_ChangeExp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_ChangeExp.Unmarshal(m, b)
}
func (m *MC_ChangeExp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_ChangeExp.Marshal(b, m, deterministic)
}
func (m *MC_ChangeExp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_ChangeExp.Merge(m, src)
}
func (m *MC_ChangeExp) XXX_Size() int {
	return xxx_messageInfo_MC_ChangeExp.Size(m)
}
func (m *MC_ChangeExp) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_ChangeExp.DiscardUnknown(m)
}

var xxx_messageInfo_MC_ChangeExp proto.InternalMessageInfo

func (m *MC_ChangeExp) GetAddExp() int64 {
	if m != nil {
		return m.AddExp
	}
	return 0
}

type MS_ExpUpdate struct {
	Exp                  int64    `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MS_ExpUpdate) Reset()         { *m = MS_ExpUpdate{} }
func (m *MS_ExpUpdate) String() string { return proto.CompactTextString(m) }
func (*MS_ExpUpdate) ProtoMessage()    {}
func (*MS_ExpUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{10}
}

func (m *MS_ExpUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_ExpUpdate.Unmarshal(m, b)
}
func (m *MS_ExpUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_ExpUpdate.Marshal(b, m, deterministic)
}
func (m *MS_ExpUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_ExpUpdate.Merge(m, src)
}
func (m *MS_ExpUpdate) XXX_Size() int {
	return xxx_messageInfo_MS_ExpUpdate.Size(m)
}
func (m *MS_ExpUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_ExpUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MS_ExpUpdate proto.InternalMessageInfo

func (m *MS_ExpUpdate) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

type MC_ChangeLevel struct {
	AddLevel             int32    `protobuf:"varint,1,opt,name=add_level,json=addLevel,proto3" json:"add_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_ChangeLevel) Reset()         { *m = MC_ChangeLevel{} }
func (m *MC_ChangeLevel) String() string { return proto.CompactTextString(m) }
func (*MC_ChangeLevel) ProtoMessage()    {}
func (*MC_ChangeLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{11}
}

func (m *MC_ChangeLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_ChangeLevel.Unmarshal(m, b)
}
func (m *MC_ChangeLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_ChangeLevel.Marshal(b, m, deterministic)
}
func (m *MC_ChangeLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_ChangeLevel.Merge(m, src)
}
func (m *MC_ChangeLevel) XXX_Size() int {
	return xxx_messageInfo_MC_ChangeLevel.Size(m)
}
func (m *MC_ChangeLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_ChangeLevel.DiscardUnknown(m)
}

var xxx_messageInfo_MC_ChangeLevel proto.InternalMessageInfo

func (m *MC_ChangeLevel) GetAddLevel() int32 {
	if m != nil {
		return m.AddLevel
	}
	return 0
}

type MS_LevelUpdate struct {
	Level                int32    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MS_LevelUpdate) Reset()         { *m = MS_LevelUpdate{} }
func (m *MS_LevelUpdate) String() string { return proto.CompactTextString(m) }
func (*MS_LevelUpdate) ProtoMessage()    {}
func (*MS_LevelUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e574b74a3b2962cb, []int{12}
}

func (m *MS_LevelUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_LevelUpdate.Unmarshal(m, b)
}
func (m *MS_LevelUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_LevelUpdate.Marshal(b, m, deterministic)
}
func (m *MS_LevelUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_LevelUpdate.Merge(m, src)
}
func (m *MS_LevelUpdate) XXX_Size() int {
	return xxx_messageInfo_MS_LevelUpdate.Size(m)
}
func (m *MS_LevelUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_LevelUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MS_LevelUpdate proto.InternalMessageInfo

func (m *MS_LevelUpdate) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerInfo)(nil), "yokai_game.PlayerInfo")
	proto.RegisterType((*MC_CreatePlayer)(nil), "yokai_game.MC_CreatePlayer")
	proto.RegisterType((*MS_CreatePlayer)(nil), "yokai_game.MS_CreatePlayer")
	proto.RegisterType((*MC_SelectPlayer)(nil), "yokai_game.MC_SelectPlayer")
	proto.RegisterType((*MS_SelectPlayer)(nil), "yokai_game.MS_SelectPlayer")
	proto.RegisterType((*MC_ExpirePlayer)(nil), "yokai_game.MC_ExpirePlayer")
	proto.RegisterType((*MC_QueryPlayerInfos)(nil), "yokai_game.MC_QueryPlayerInfos")
	proto.RegisterType((*MS_QueryPlayerInfo)(nil), "yokai_game.MS_QueryPlayerInfo")
	proto.RegisterType((*MS_QueryPlayerInfos)(nil), "yokai_game.MS_QueryPlayerInfos")
	proto.RegisterType((*MC_ChangeExp)(nil), "yokai_game.MC_ChangeExp")
	proto.RegisterType((*MS_ExpUpdate)(nil), "yokai_game.MS_ExpUpdate")
	proto.RegisterType((*MC_ChangeLevel)(nil), "yokai_game.MC_ChangeLevel")
	proto.RegisterType((*MS_LevelUpdate)(nil), "yokai_game.MS_LevelUpdate")
}

func init() { proto.RegisterFile("game/player.proto", fileDescriptor_e574b74a3b2962cb) }

var fileDescriptor_e574b74a3b2962cb = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xed, 0x8a, 0xd3, 0x40,
	0x14, 0x65, 0xda, 0xa6, 0xda, 0xeb, 0xd2, 0x75, 0x67, 0xfd, 0x08, 0x88, 0x10, 0x07, 0xd4, 0xb2,
	0xac, 0x2d, 0xe8, 0x0b, 0x88, 0xa1, 0x3f, 0x04, 0x23, 0x9a, 0xe0, 0x1f, 0x11, 0x86, 0xd9, 0xce,
	0xdd, 0x76, 0xb0, 0xc9, 0x84, 0x49, 0xb2, 0xa4, 0xaf, 0xe1, 0x13, 0xcb, 0xcc, 0xc4, 0xc4, 0xad,
	0x20, 0x08, 0xfe, 0xca, 0xcd, 0x3d, 0x87, 0xc3, 0x39, 0x37, 0x27, 0x70, 0xb6, 0x15, 0x39, 0xae,
	0xca, 0xbd, 0x38, 0xa0, 0x59, 0x96, 0x46, 0xd7, 0x9a, 0xc2, 0x41, 0x7f, 0x17, 0x8a, 0x5b, 0x80,
	0xfd, 0x20, 0x00, 0x9f, 0x1c, 0xf8, 0xbe, 0xb8, 0xd6, 0x74, 0x0e, 0x23, 0x25, 0x43, 0x12, 0x91,
	0xc5, 0x38, 0x1d, 0x29, 0x49, 0x29, 0x4c, 0x0a, 0x91, 0x63, 0x38, 0x8a, 0xc8, 0x62, 0x96, 0xba,
	0x99, 0xde, 0x87, 0x31, 0xb6, 0x65, 0x38, 0x76, 0x24, 0x3b, 0xd2, 0x07, 0x10, 0xec, 0xf1, 0x06,
	0xf7, 0xe1, 0x24, 0x22, 0x8b, 0x20, 0xf5, 0x2f, 0xf4, 0x09, 0xcc, 0x76, 0x68, 0x34, 0x2f, 0x9a,
	0xbc, 0x0a, 0x03, 0x87, 0xdc, 0xb5, 0x8b, 0x8f, 0x4d, 0x5e, 0x59, 0x50, 0xd5, 0x98, 0x7b, 0x70,
	0xea, 0x41, 0xbb, 0xb0, 0x20, 0x7b, 0x0e, 0xa7, 0x49, 0xcc, 0x63, 0x83, 0xa2, 0x46, 0x6f, 0xae,
	0x37, 0x42, 0x06, 0x23, 0xec, 0x1b, 0x9c, 0x26, 0xd9, 0x6d, 0xda, 0x05, 0x4c, 0x54, 0x71, 0xad,
	0x1d, 0xed, 0xde, 0xeb, 0x47, 0xcb, 0x21, 0xe9, 0x72, 0x48, 0x99, 0x3a, 0x0e, 0x7d, 0x0a, 0x80,
	0xc6, 0x68, 0xc3, 0x37, 0x5a, 0xfa, 0x84, 0x41, 0x3a, 0x73, 0x9b, 0x58, 0x4b, 0x64, 0xcf, 0x9c,
	0x89, 0x0c, 0xf7, 0xb8, 0xa9, 0x3b, 0xf5, 0xa3, 0xeb, 0x74, 0x06, 0x6e, 0x51, 0xfe, 0xa3, 0x81,
	0x33, 0x67, 0x60, 0xdd, 0x96, 0xca, 0x74, 0xf1, 0xd8, 0x43, 0x38, 0x4f, 0x62, 0xfe, 0xb9, 0x41,
	0x73, 0x18, 0xd4, 0x2a, 0xf6, 0x16, 0x68, 0x92, 0x1d, 0xaf, 0xff, 0xc5, 0x0a, 0x8b, 0xe1, 0xfc,
	0x4f, 0x85, 0x8a, 0x5e, 0x42, 0x60, 0xe1, 0x2a, 0x24, 0xd1, 0xf8, 0x2f, 0x1a, 0x9e, 0xc4, 0x5e,
	0xc2, 0x89, 0xfd, 0x6c, 0x3b, 0x51, 0x6c, 0x71, 0xdd, 0x96, 0xf4, 0x31, 0xdc, 0x11, 0x52, 0x72,
	0x5b, 0x16, 0x7f, 0xb3, 0xa9, 0x90, 0x72, 0xdd, 0x96, 0x2c, 0x82, 0x93, 0x24, 0xb3, 0xc9, 0xbe,
	0x94, 0x52, 0xd4, 0x7d, 0xa3, 0x48, 0xdf, 0x28, 0xf6, 0x0a, 0xe6, 0xbd, 0xd4, 0x87, 0x5f, 0x6d,
	0xb2, 0x62, 0xbe, 0x67, 0xc4, 0x17, 0x46, 0x48, 0xe9, 0x40, 0xf6, 0x02, 0xe6, 0x49, 0xc6, 0xdd,
	0xdc, 0x49, 0xf6, 0x95, 0x24, 0xbf, 0x55, 0xf2, 0xdd, 0xe5, 0xd7, 0x8b, 0xad, 0xaa, 0x77, 0xcd,
	0xd5, 0x72, 0xa3, 0xf3, 0x95, 0x0b, 0xa3, 0xb4, 0x7f, 0xf2, 0x0a, 0xcd, 0x0d, 0x9a, 0x95, 0xfb,
	0x45, 0x56, 0x36, 0xe1, 0xd5, 0xd4, 0xcd, 0x6f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xef,
	0x5c, 0xa4, 0x43, 0x03, 0x00, 0x00,
}
