// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/rune.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// Rune
type RuneAtt struct {
	AttType              int32    `protobuf:"varint,1,opt,name=AttType,proto3" json:"AttType,omitempty"`
	AttValue             int64    `protobuf:"varint,2,opt,name=AttValue,proto3" json:"AttValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuneAtt) Reset()         { *m = RuneAtt{} }
func (m *RuneAtt) String() string { return proto.CompactTextString(m) }
func (*RuneAtt) ProtoMessage()    {}
func (*RuneAtt) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{0}
}

func (m *RuneAtt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuneAtt.Unmarshal(m, b)
}
func (m *RuneAtt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuneAtt.Marshal(b, m, deterministic)
}
func (m *RuneAtt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuneAtt.Merge(m, src)
}
func (m *RuneAtt) XXX_Size() int {
	return xxx_messageInfo_RuneAtt.Size(m)
}
func (m *RuneAtt) XXX_DiscardUnknown() {
	xxx_messageInfo_RuneAtt.DiscardUnknown(m)
}

var xxx_messageInfo_RuneAtt proto.InternalMessageInfo

func (m *RuneAtt) GetAttType() int32 {
	if m != nil {
		return m.AttType
	}
	return 0
}

func (m *RuneAtt) GetAttValue() int64 {
	if m != nil {
		return m.AttValue
	}
	return 0
}

type Rune struct {
	Id                   int64      `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TypeId               int32      `protobuf:"varint,2,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	EquipObjId           int64      `protobuf:"varint,3,opt,name=EquipObjId,proto3" json:"EquipObjId,omitempty"`
	Atts                 []*RuneAtt `protobuf:"bytes,4,rep,name=Atts,proto3" json:"Atts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Rune) Reset()         { *m = Rune{} }
func (m *Rune) String() string { return proto.CompactTextString(m) }
func (*Rune) ProtoMessage()    {}
func (*Rune) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{1}
}

func (m *Rune) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rune.Unmarshal(m, b)
}
func (m *Rune) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rune.Marshal(b, m, deterministic)
}
func (m *Rune) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rune.Merge(m, src)
}
func (m *Rune) XXX_Size() int {
	return xxx_messageInfo_Rune.Size(m)
}
func (m *Rune) XXX_DiscardUnknown() {
	xxx_messageInfo_Rune.DiscardUnknown(m)
}

var xxx_messageInfo_Rune proto.InternalMessageInfo

func (m *Rune) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rune) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Rune) GetEquipObjId() int64 {
	if m != nil {
		return m.EquipObjId
	}
	return 0
}

func (m *Rune) GetAtts() []*RuneAtt {
	if m != nil {
		return m.Atts
	}
	return nil
}

type C2M_AddRune struct {
	TypeId               int32    `protobuf:"varint,1,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_AddRune) Reset()         { *m = C2M_AddRune{} }
func (m *C2M_AddRune) String() string { return proto.CompactTextString(m) }
func (*C2M_AddRune) ProtoMessage()    {}
func (*C2M_AddRune) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{2}
}

func (m *C2M_AddRune) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_AddRune.Unmarshal(m, b)
}
func (m *C2M_AddRune) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_AddRune.Marshal(b, m, deterministic)
}
func (m *C2M_AddRune) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_AddRune.Merge(m, src)
}
func (m *C2M_AddRune) XXX_Size() int {
	return xxx_messageInfo_C2M_AddRune.Size(m)
}
func (m *C2M_AddRune) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_AddRune.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_AddRune proto.InternalMessageInfo

func (m *C2M_AddRune) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type C2M_DelRune struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_DelRune) Reset()         { *m = C2M_DelRune{} }
func (m *C2M_DelRune) String() string { return proto.CompactTextString(m) }
func (*C2M_DelRune) ProtoMessage()    {}
func (*C2M_DelRune) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{3}
}

func (m *C2M_DelRune) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_DelRune.Unmarshal(m, b)
}
func (m *C2M_DelRune) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_DelRune.Marshal(b, m, deterministic)
}
func (m *C2M_DelRune) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_DelRune.Merge(m, src)
}
func (m *C2M_DelRune) XXX_Size() int {
	return xxx_messageInfo_C2M_DelRune.Size(m)
}
func (m *C2M_DelRune) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_DelRune.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_DelRune proto.InternalMessageInfo

func (m *C2M_DelRune) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type C2M_QueryRunes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryRunes) Reset()         { *m = C2M_QueryRunes{} }
func (m *C2M_QueryRunes) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryRunes) ProtoMessage()    {}
func (*C2M_QueryRunes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{4}
}

func (m *C2M_QueryRunes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryRunes.Unmarshal(m, b)
}
func (m *C2M_QueryRunes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryRunes.Marshal(b, m, deterministic)
}
func (m *C2M_QueryRunes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryRunes.Merge(m, src)
}
func (m *C2M_QueryRunes) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryRunes.Size(m)
}
func (m *C2M_QueryRunes) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryRunes.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryRunes proto.InternalMessageInfo

type M2C_RuneList struct {
	Runes                []*Rune  `protobuf:"bytes,1,rep,name=runes,proto3" json:"runes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_RuneList) Reset()         { *m = M2C_RuneList{} }
func (m *M2C_RuneList) String() string { return proto.CompactTextString(m) }
func (*M2C_RuneList) ProtoMessage()    {}
func (*M2C_RuneList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{5}
}

func (m *M2C_RuneList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_RuneList.Unmarshal(m, b)
}
func (m *M2C_RuneList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_RuneList.Marshal(b, m, deterministic)
}
func (m *M2C_RuneList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_RuneList.Merge(m, src)
}
func (m *M2C_RuneList) XXX_Size() int {
	return xxx_messageInfo_M2C_RuneList.Size(m)
}
func (m *M2C_RuneList) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_RuneList.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_RuneList proto.InternalMessageInfo

func (m *M2C_RuneList) GetRunes() []*Rune {
	if m != nil {
		return m.Runes
	}
	return nil
}

type M2C_RuneAdd struct {
	Rune                 *Rune    `protobuf:"bytes,1,opt,name=rune,proto3" json:"rune,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_RuneAdd) Reset()         { *m = M2C_RuneAdd{} }
func (m *M2C_RuneAdd) String() string { return proto.CompactTextString(m) }
func (*M2C_RuneAdd) ProtoMessage()    {}
func (*M2C_RuneAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{6}
}

func (m *M2C_RuneAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_RuneAdd.Unmarshal(m, b)
}
func (m *M2C_RuneAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_RuneAdd.Marshal(b, m, deterministic)
}
func (m *M2C_RuneAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_RuneAdd.Merge(m, src)
}
func (m *M2C_RuneAdd) XXX_Size() int {
	return xxx_messageInfo_M2C_RuneAdd.Size(m)
}
func (m *M2C_RuneAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_RuneAdd.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_RuneAdd proto.InternalMessageInfo

func (m *M2C_RuneAdd) GetRune() *Rune {
	if m != nil {
		return m.Rune
	}
	return nil
}

type M2C_RuneUpdate struct {
	Rune                 *Rune    `protobuf:"bytes,1,opt,name=rune,proto3" json:"rune,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_RuneUpdate) Reset()         { *m = M2C_RuneUpdate{} }
func (m *M2C_RuneUpdate) String() string { return proto.CompactTextString(m) }
func (*M2C_RuneUpdate) ProtoMessage()    {}
func (*M2C_RuneUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{7}
}

func (m *M2C_RuneUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_RuneUpdate.Unmarshal(m, b)
}
func (m *M2C_RuneUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_RuneUpdate.Marshal(b, m, deterministic)
}
func (m *M2C_RuneUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_RuneUpdate.Merge(m, src)
}
func (m *M2C_RuneUpdate) XXX_Size() int {
	return xxx_messageInfo_M2C_RuneUpdate.Size(m)
}
func (m *M2C_RuneUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_RuneUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_RuneUpdate proto.InternalMessageInfo

func (m *M2C_RuneUpdate) GetRune() *Rune {
	if m != nil {
		return m.Rune
	}
	return nil
}

type M2C_DelRune struct {
	RuneId               int64    `protobuf:"varint,1,opt,name=RuneId,proto3" json:"RuneId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_DelRune) Reset()         { *m = M2C_DelRune{} }
func (m *M2C_DelRune) String() string { return proto.CompactTextString(m) }
func (*M2C_DelRune) ProtoMessage()    {}
func (*M2C_DelRune) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{8}
}

func (m *M2C_DelRune) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_DelRune.Unmarshal(m, b)
}
func (m *M2C_DelRune) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_DelRune.Marshal(b, m, deterministic)
}
func (m *M2C_DelRune) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_DelRune.Merge(m, src)
}
func (m *M2C_DelRune) XXX_Size() int {
	return xxx_messageInfo_M2C_DelRune.Size(m)
}
func (m *M2C_DelRune) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_DelRune.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_DelRune proto.InternalMessageInfo

func (m *M2C_DelRune) GetRuneId() int64 {
	if m != nil {
		return m.RuneId
	}
	return 0
}

type C2M_PutonRune struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	RuneId               int64    `protobuf:"varint,2,opt,name=RuneId,proto3" json:"RuneId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_PutonRune) Reset()         { *m = C2M_PutonRune{} }
func (m *C2M_PutonRune) String() string { return proto.CompactTextString(m) }
func (*C2M_PutonRune) ProtoMessage()    {}
func (*C2M_PutonRune) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{9}
}

func (m *C2M_PutonRune) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_PutonRune.Unmarshal(m, b)
}
func (m *C2M_PutonRune) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_PutonRune.Marshal(b, m, deterministic)
}
func (m *C2M_PutonRune) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_PutonRune.Merge(m, src)
}
func (m *C2M_PutonRune) XXX_Size() int {
	return xxx_messageInfo_C2M_PutonRune.Size(m)
}
func (m *C2M_PutonRune) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_PutonRune.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_PutonRune proto.InternalMessageInfo

func (m *C2M_PutonRune) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *C2M_PutonRune) GetRuneId() int64 {
	if m != nil {
		return m.RuneId
	}
	return 0
}

type C2M_TakeoffRune struct {
	HeroId               int64    `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	Pos                  int32    `protobuf:"varint,2,opt,name=Pos,proto3" json:"Pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_TakeoffRune) Reset()         { *m = C2M_TakeoffRune{} }
func (m *C2M_TakeoffRune) String() string { return proto.CompactTextString(m) }
func (*C2M_TakeoffRune) ProtoMessage()    {}
func (*C2M_TakeoffRune) Descriptor() ([]byte, []int) {
	return fileDescriptor_6057880d33e6ad5b, []int{10}
}

func (m *C2M_TakeoffRune) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_TakeoffRune.Unmarshal(m, b)
}
func (m *C2M_TakeoffRune) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_TakeoffRune.Marshal(b, m, deterministic)
}
func (m *C2M_TakeoffRune) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_TakeoffRune.Merge(m, src)
}
func (m *C2M_TakeoffRune) XXX_Size() int {
	return xxx_messageInfo_C2M_TakeoffRune.Size(m)
}
func (m *C2M_TakeoffRune) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_TakeoffRune.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_TakeoffRune proto.InternalMessageInfo

func (m *C2M_TakeoffRune) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *C2M_TakeoffRune) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func init() {
	proto.RegisterType((*RuneAtt)(nil), "game.RuneAtt")
	proto.RegisterType((*Rune)(nil), "game.Rune")
	proto.RegisterType((*C2M_AddRune)(nil), "game.C2M_AddRune")
	proto.RegisterType((*C2M_DelRune)(nil), "game.C2M_DelRune")
	proto.RegisterType((*C2M_QueryRunes)(nil), "game.C2M_QueryRunes")
	proto.RegisterType((*M2C_RuneList)(nil), "game.M2C_RuneList")
	proto.RegisterType((*M2C_RuneAdd)(nil), "game.M2C_RuneAdd")
	proto.RegisterType((*M2C_RuneUpdate)(nil), "game.M2C_RuneUpdate")
	proto.RegisterType((*M2C_DelRune)(nil), "game.M2C_DelRune")
	proto.RegisterType((*C2M_PutonRune)(nil), "game.C2M_PutonRune")
	proto.RegisterType((*C2M_TakeoffRune)(nil), "game.C2M_TakeoffRune")
}

func init() { proto.RegisterFile("game/rune.proto", fileDescriptor_6057880d33e6ad5b) }

var fileDescriptor_6057880d33e6ad5b = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4b, 0x6b, 0xea, 0x40,
	0x14, 0x26, 0x0f, 0xf5, 0x72, 0xbc, 0x3e, 0x98, 0x85, 0x84, 0x0b, 0xb7, 0xa4, 0x03, 0x96, 0x6c,
	0x4c, 0xc4, 0x2e, 0xbb, 0x90, 0xd4, 0x16, 0x1a, 0xa8, 0xd4, 0x06, 0xdb, 0x45, 0x37, 0x12, 0x3b,
	0xa3, 0xb5, 0xd5, 0x24, 0x26, 0x93, 0x82, 0xff, 0xbe, 0x9c, 0x49, 0xe2, 0x03, 0x4a, 0xbb, 0xca,
	0x7c, 0x67, 0xbe, 0xf3, 0x3d, 0x92, 0x40, 0x6b, 0x19, 0x6c, 0xb8, 0x93, 0x64, 0x21, 0xb7, 0xe3,
	0x24, 0x12, 0x11, 0xd1, 0x71, 0x40, 0x87, 0x50, 0xf3, 0xb3, 0x90, 0xbb, 0x42, 0x10, 0x03, 0x6a,
	0xae, 0x10, 0xd3, 0x5d, 0xcc, 0x0d, 0xc5, 0x54, 0xac, 0x8a, 0x5f, 0x42, 0xf2, 0x0f, 0xfe, 0xb8,
	0x42, 0x3c, 0x07, 0xeb, 0x8c, 0x1b, 0xaa, 0xa9, 0x58, 0x9a, 0xbf, 0xc7, 0x74, 0x0b, 0x3a, 0x0a,
	0x90, 0x26, 0xa8, 0x1e, 0x93, 0x8b, 0x9a, 0xaf, 0x7a, 0x8c, 0x74, 0xa0, 0x8a, 0xbb, 0x1e, 0x93,
	0x1b, 0x15, 0xbf, 0x40, 0xe4, 0x0c, 0xe0, 0x76, 0x9b, 0xad, 0xe2, 0x87, 0xf9, 0xbb, 0xc7, 0x0c,
	0x4d, 0xf2, 0x8f, 0x26, 0xe4, 0x1c, 0x74, 0x57, 0x88, 0xd4, 0xd0, 0x4d, 0xcd, 0xaa, 0x0f, 0x1a,
	0x36, 0xa6, 0xb4, 0x8b, 0x88, 0xbe, 0xbc, 0xa2, 0x5d, 0xa8, 0x8f, 0x06, 0xe3, 0x99, 0xcb, 0x98,
	0x74, 0x3e, 0x38, 0x29, 0xc7, 0x4e, 0xf4, 0x7f, 0x4e, 0xbb, 0xe1, 0xeb, 0xef, 0x02, 0xd2, 0x36,
	0x34, 0xf1, 0xfa, 0x31, 0xe3, 0xc9, 0x0e, 0x09, 0x29, 0xed, 0xc3, 0xdf, 0xf1, 0x60, 0x34, 0x43,
	0x70, 0xbf, 0x4a, 0x05, 0x31, 0xa1, 0x82, 0xef, 0x2b, 0x35, 0x14, 0x99, 0x05, 0x0e, 0x59, 0xfc,
	0xfc, 0x82, 0xf6, 0xa0, 0x5e, 0x6e, 0xb8, 0x0c, 0xbb, 0xe9, 0x38, 0x97, 0x26, 0xa7, 0x7c, 0x39,
	0xa7, 0x7d, 0x68, 0x96, 0xf4, 0xa7, 0x98, 0x05, 0x82, 0xff, 0xba, 0xd1, 0xcd, 0x0d, 0xca, 0x0e,
	0x1d, 0xa8, 0xe2, 0x73, 0xdf, 0xa3, 0x40, 0x74, 0x08, 0x0d, 0xec, 0x32, 0xc9, 0x44, 0x14, 0x96,
	0xc4, 0x3b, 0x9e, 0x44, 0x07, 0x62, 0x8e, 0x8e, 0x04, 0xd4, 0x13, 0x81, 0x2b, 0x68, 0xa1, 0xc0,
	0x34, 0xf8, 0xe0, 0xd1, 0x62, 0xf1, 0xa3, 0x44, 0x1b, 0xb4, 0x49, 0x94, 0x16, 0x5f, 0x15, 0x8f,
	0xd7, 0xd6, 0xcb, 0xc5, 0x72, 0x25, 0xde, 0xb2, 0xb9, 0xfd, 0x1a, 0x6d, 0x1c, 0x1e, 0xa4, 0xa2,
	0xc7, 0x19, 0x0f, 0x9d, 0x94, 0x27, 0x9f, 0x3c, 0x71, 0xe4, 0xef, 0xe6, 0x60, 0xb3, 0x79, 0x55,
	0x9e, 0x2f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x22, 0x51, 0xa0, 0x8d, 0x02, 0x00, 0x00,
}
