// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: game/scene.proto

package game

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

////////////////////////////////////////////////
// scene
type C2M_StartStageCombat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
}

func (x *C2M_StartStageCombat) Reset() {
	*x = C2M_StartStageCombat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_scene_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2M_StartStageCombat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_StartStageCombat) ProtoMessage() {}

func (x *C2M_StartStageCombat) ProtoReflect() protoreflect.Message {
	mi := &file_game_scene_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_StartStageCombat.ProtoReflect.Descriptor instead.
func (*C2M_StartStageCombat) Descriptor() ([]byte, []int) {
	return file_game_scene_proto_rawDescGZIP(), []int{0}
}

func (x *C2M_StartStageCombat) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type M2C_StartStageCombat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32  `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error   int32  `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message string `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Result  bool   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *M2C_StartStageCombat) Reset() {
	*x = M2C_StartStageCombat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_scene_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *M2C_StartStageCombat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_StartStageCombat) ProtoMessage() {}

func (x *M2C_StartStageCombat) ProtoReflect() protoreflect.Message {
	mi := &file_game_scene_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_StartStageCombat.ProtoReflect.Descriptor instead.
func (*M2C_StartStageCombat) Descriptor() ([]byte, []int) {
	return file_game_scene_proto_rawDescGZIP(), []int{1}
}

func (x *M2C_StartStageCombat) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2C_StartStageCombat) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2C_StartStageCombat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *M2C_StartStageCombat) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_game_scene_proto protoreflect.FileDescriptor

var file_game_scene_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x14, 0x43, 0x32, 0x4d, 0x5f,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x14, 0x4d, 0x32, 0x43, 0x5f, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52,
	0x70, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x5b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x5c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x2f, 0x5a, 0x2d,
	0x65, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x6d, 0x6d, 0x73,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x2f, 0x62, 0x6c, 0x61, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x5f, 0x6f, 0x75, 0x74, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_scene_proto_rawDescOnce sync.Once
	file_game_scene_proto_rawDescData = file_game_scene_proto_rawDesc
)

func file_game_scene_proto_rawDescGZIP() []byte {
	file_game_scene_proto_rawDescOnce.Do(func() {
		file_game_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_scene_proto_rawDescData)
	})
	return file_game_scene_proto_rawDescData
}

var file_game_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_scene_proto_goTypes = []interface{}{
	(*C2M_StartStageCombat)(nil), // 0: game.C2M_StartStageCombat
	(*M2C_StartStageCombat)(nil), // 1: game.M2C_StartStageCombat
}
var file_game_scene_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_scene_proto_init() }
func file_game_scene_proto_init() {
	if File_game_scene_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_scene_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2M_StartStageCombat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_scene_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*M2C_StartStageCombat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_scene_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_scene_proto_goTypes,
		DependencyIndexes: file_game_scene_proto_depIdxs,
		MessageInfos:      file_game_scene_proto_msgTypes,
	}.Build()
	File_game_scene_proto = out.File
	file_game_scene_proto_rawDesc = nil
	file_game_scene_proto_goTypes = nil
	file_game_scene_proto_depIdxs = nil
}
