// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: game/talent.proto

package game

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

////////////////////////////////////////////////
// Talent
type Talent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Talent) Reset() {
	*x = Talent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_talent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Talent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Talent) ProtoMessage() {}

func (x *Talent) ProtoReflect() protoreflect.Message {
	mi := &file_game_talent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Talent.ProtoReflect.Descriptor instead.
func (*Talent) Descriptor() ([]byte, []int) {
	return file_game_talent_proto_rawDescGZIP(), []int{0}
}

func (x *Talent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type C2M_AddTalent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BladeId  int64 `protobuf:"varint,1,opt,name=BladeId,proto3" json:"BladeId,omitempty"`
	TalentId int32 `protobuf:"varint,2,opt,name=TalentId,proto3" json:"TalentId,omitempty"`
}

func (x *C2M_AddTalent) Reset() {
	*x = C2M_AddTalent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_talent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2M_AddTalent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_AddTalent) ProtoMessage() {}

func (x *C2M_AddTalent) ProtoReflect() protoreflect.Message {
	mi := &file_game_talent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_AddTalent.ProtoReflect.Descriptor instead.
func (*C2M_AddTalent) Descriptor() ([]byte, []int) {
	return file_game_talent_proto_rawDescGZIP(), []int{1}
}

func (x *C2M_AddTalent) GetBladeId() int64 {
	if x != nil {
		return x.BladeId
	}
	return 0
}

func (x *C2M_AddTalent) GetTalentId() int32 {
	if x != nil {
		return x.TalentId
	}
	return 0
}

type C2M_QueryTalents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BladeId int64 `protobuf:"varint,1,opt,name=BladeId,proto3" json:"BladeId,omitempty"`
}

func (x *C2M_QueryTalents) Reset() {
	*x = C2M_QueryTalents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_talent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2M_QueryTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_QueryTalents) ProtoMessage() {}

func (x *C2M_QueryTalents) ProtoReflect() protoreflect.Message {
	mi := &file_game_talent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_QueryTalents.ProtoReflect.Descriptor instead.
func (*C2M_QueryTalents) Descriptor() ([]byte, []int) {
	return file_game_talent_proto_rawDescGZIP(), []int{2}
}

func (x *C2M_QueryTalents) GetBladeId() int64 {
	if x != nil {
		return x.BladeId
	}
	return 0
}

type M2C_TalentList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BladeId int64     `protobuf:"varint,1,opt,name=BladeId,proto3" json:"BladeId,omitempty"`
	Talents []*Talent `protobuf:"bytes,2,rep,name=Talents,proto3" json:"Talents,omitempty"`
}

func (x *M2C_TalentList) Reset() {
	*x = M2C_TalentList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_talent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *M2C_TalentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_TalentList) ProtoMessage() {}

func (x *M2C_TalentList) ProtoReflect() protoreflect.Message {
	mi := &file_game_talent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_TalentList.ProtoReflect.Descriptor instead.
func (*M2C_TalentList) Descriptor() ([]byte, []int) {
	return file_game_talent_proto_rawDescGZIP(), []int{3}
}

func (x *M2C_TalentList) GetBladeId() int64 {
	if x != nil {
		return x.BladeId
	}
	return 0
}

func (x *M2C_TalentList) GetTalents() []*Talent {
	if x != nil {
		return x.Talents
	}
	return nil
}

var File_game_talent_proto protoreflect.FileDescriptor

var file_game_talent_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x18, 0x0a, 0x06, 0x54, 0x61, 0x6c,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0d, 0x43, 0x32, 0x4d, 0x5f, 0x41, 0x64, 0x64, 0x54, 0x61,
	0x6c, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x61, 0x64, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x6c, 0x61, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x43, 0x32,
	0x4d, 0x5f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x42, 0x6c, 0x61, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x42, 0x6c, 0x61, 0x64, 0x65, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x0e, 0x4d, 0x32, 0x43, 0x5f,
	0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c,
	0x61, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x6c, 0x61,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x6c,
	0x65, 0x6e, 0x74, 0x52, 0x07, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x2f, 0x5a, 0x2d,
	0x65, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x6d, 0x6d, 0x73,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x2f, 0x62, 0x6c, 0x61, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x5f, 0x6f, 0x75, 0x74, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_talent_proto_rawDescOnce sync.Once
	file_game_talent_proto_rawDescData = file_game_talent_proto_rawDesc
)

func file_game_talent_proto_rawDescGZIP() []byte {
	file_game_talent_proto_rawDescOnce.Do(func() {
		file_game_talent_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_talent_proto_rawDescData)
	})
	return file_game_talent_proto_rawDescData
}

var file_game_talent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_game_talent_proto_goTypes = []interface{}{
	(*Talent)(nil),           // 0: game.Talent
	(*C2M_AddTalent)(nil),    // 1: game.C2M_AddTalent
	(*C2M_QueryTalents)(nil), // 2: game.C2M_QueryTalents
	(*M2C_TalentList)(nil),   // 3: game.M2C_TalentList
}
var file_game_talent_proto_depIdxs = []int32{
	0, // 0: game.M2C_TalentList.Talents:type_name -> game.Talent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_talent_proto_init() }
func file_game_talent_proto_init() {
	if File_game_talent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_talent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Talent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_talent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2M_AddTalent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_talent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2M_QueryTalents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_talent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*M2C_TalentList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_talent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_talent_proto_goTypes,
		DependencyIndexes: file_game_talent_proto_depIdxs,
		MessageInfos:      file_game_talent_proto_msgTypes,
	}.Build()
	File_game_talent_proto = out.File
	file_game_talent_proto_rawDesc = nil
	file_game_talent_proto_goTypes = nil
	file_game_talent_proto_depIdxs = nil
}
