// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/talent.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// Talent
type Talent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Talent) Reset()         { *m = Talent{} }
func (m *Talent) String() string { return proto.CompactTextString(m) }
func (*Talent) ProtoMessage()    {}
func (*Talent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f418930e25cfdcc, []int{0}
}

func (m *Talent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Talent.Unmarshal(m, b)
}
func (m *Talent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Talent.Marshal(b, m, deterministic)
}
func (m *Talent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Talent.Merge(m, src)
}
func (m *Talent) XXX_Size() int {
	return xxx_messageInfo_Talent.Size(m)
}
func (m *Talent) XXX_DiscardUnknown() {
	xxx_messageInfo_Talent.DiscardUnknown(m)
}

var xxx_messageInfo_Talent proto.InternalMessageInfo

func (m *Talent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MC_AddTalent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_AddTalent) Reset()         { *m = MC_AddTalent{} }
func (m *MC_AddTalent) String() string { return proto.CompactTextString(m) }
func (*MC_AddTalent) ProtoMessage()    {}
func (*MC_AddTalent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f418930e25cfdcc, []int{1}
}

func (m *MC_AddTalent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_AddTalent.Unmarshal(m, b)
}
func (m *MC_AddTalent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_AddTalent.Marshal(b, m, deterministic)
}
func (m *MC_AddTalent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_AddTalent.Merge(m, src)
}
func (m *MC_AddTalent) XXX_Size() int {
	return xxx_messageInfo_MC_AddTalent.Size(m)
}
func (m *MC_AddTalent) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_AddTalent.DiscardUnknown(m)
}

var xxx_messageInfo_MC_AddTalent proto.InternalMessageInfo

func (m *MC_AddTalent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MC_QueryTalents struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_QueryTalents) Reset()         { *m = MC_QueryTalents{} }
func (m *MC_QueryTalents) String() string { return proto.CompactTextString(m) }
func (*MC_QueryTalents) ProtoMessage()    {}
func (*MC_QueryTalents) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f418930e25cfdcc, []int{2}
}

func (m *MC_QueryTalents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_QueryTalents.Unmarshal(m, b)
}
func (m *MC_QueryTalents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_QueryTalents.Marshal(b, m, deterministic)
}
func (m *MC_QueryTalents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_QueryTalents.Merge(m, src)
}
func (m *MC_QueryTalents) XXX_Size() int {
	return xxx_messageInfo_MC_QueryTalents.Size(m)
}
func (m *MC_QueryTalents) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_QueryTalents.DiscardUnknown(m)
}

var xxx_messageInfo_MC_QueryTalents proto.InternalMessageInfo

type MS_TalentList struct {
	Talents              []*Talent `protobuf:"bytes,1,rep,name=talents,proto3" json:"talents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MS_TalentList) Reset()         { *m = MS_TalentList{} }
func (m *MS_TalentList) String() string { return proto.CompactTextString(m) }
func (*MS_TalentList) ProtoMessage()    {}
func (*MS_TalentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f418930e25cfdcc, []int{3}
}

func (m *MS_TalentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_TalentList.Unmarshal(m, b)
}
func (m *MS_TalentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_TalentList.Marshal(b, m, deterministic)
}
func (m *MS_TalentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_TalentList.Merge(m, src)
}
func (m *MS_TalentList) XXX_Size() int {
	return xxx_messageInfo_MS_TalentList.Size(m)
}
func (m *MS_TalentList) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_TalentList.DiscardUnknown(m)
}

var xxx_messageInfo_MS_TalentList proto.InternalMessageInfo

func (m *MS_TalentList) GetTalents() []*Talent {
	if m != nil {
		return m.Talents
	}
	return nil
}

func init() {
	proto.RegisterType((*Talent)(nil), "yokai_game.Talent")
	proto.RegisterType((*MC_AddTalent)(nil), "yokai_game.MC_AddTalent")
	proto.RegisterType((*MC_QueryTalents)(nil), "yokai_game.MC_QueryTalents")
	proto.RegisterType((*MS_TalentList)(nil), "yokai_game.MS_TalentList")
}

func init() { proto.RegisterFile("game/talent.proto", fileDescriptor_0f418930e25cfdcc) }

var fileDescriptor_0f418930e25cfdcc = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2f, 0x49, 0xcc, 0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xaa,
	0xcc, 0xcf, 0x4e, 0xcc, 0x8c, 0x07, 0x49, 0x28, 0x49, 0x70, 0xb1, 0x85, 0x80, 0xe5, 0x84, 0xf8,
	0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x94, 0xe4,
	0xb8, 0x78, 0x7c, 0x9d, 0xe3, 0x1d, 0x53, 0x52, 0x70, 0xc8, 0x0b, 0x72, 0xf1, 0xfb, 0x3a, 0xc7,
	0x07, 0x96, 0xa6, 0x16, 0x55, 0x42, 0x54, 0x14, 0x2b, 0xd9, 0x72, 0xf1, 0xfa, 0x06, 0xc7, 0x43,
	0x78, 0x3e, 0x99, 0xc5, 0x25, 0x42, 0x3a, 0x5c, 0xec, 0x10, 0x9b, 0x8b, 0x25, 0x18, 0x15, 0x98,
	0x35, 0xb8, 0x8d, 0x84, 0xf4, 0x10, 0x76, 0xeb, 0x41, 0x14, 0x06, 0xc1, 0x94, 0x38, 0xe9, 0x44,
	0x69, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x83, 0x15, 0x66, 0xe6,
	0x43, 0xe8, 0xf8, 0xe2, 0xd4, 0xa2, 0xb2, 0xd4, 0x22, 0x7d, 0xb0, 0x07, 0xf4, 0x41, 0xba, 0x93,
	0xd8, 0xc0, 0x6c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x27, 0xee, 0x00, 0xe1, 0x00,
	0x00, 0x00,
}
