// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/talent.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////
// Talent
type Talent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Talent) Reset()         { *m = Talent{} }
func (m *Talent) String() string { return proto.CompactTextString(m) }
func (*Talent) ProtoMessage()    {}
func (*Talent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f418930e25cfdcc, []int{0}
}

func (m *Talent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Talent.Unmarshal(m, b)
}
func (m *Talent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Talent.Marshal(b, m, deterministic)
}
func (m *Talent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Talent.Merge(m, src)
}
func (m *Talent) XXX_Size() int {
	return xxx_messageInfo_Talent.Size(m)
}
func (m *Talent) XXX_DiscardUnknown() {
	xxx_messageInfo_Talent.DiscardUnknown(m)
}

var xxx_messageInfo_Talent proto.InternalMessageInfo

func (m *Talent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type C2M_AddTalent struct {
	BladeId              int64    `protobuf:"varint,1,opt,name=BladeId,proto3" json:"BladeId,omitempty"`
	TalentId             int32    `protobuf:"varint,2,opt,name=TalentId,proto3" json:"TalentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_AddTalent) Reset()         { *m = C2M_AddTalent{} }
func (m *C2M_AddTalent) String() string { return proto.CompactTextString(m) }
func (*C2M_AddTalent) ProtoMessage()    {}
func (*C2M_AddTalent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f418930e25cfdcc, []int{1}
}

func (m *C2M_AddTalent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_AddTalent.Unmarshal(m, b)
}
func (m *C2M_AddTalent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_AddTalent.Marshal(b, m, deterministic)
}
func (m *C2M_AddTalent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_AddTalent.Merge(m, src)
}
func (m *C2M_AddTalent) XXX_Size() int {
	return xxx_messageInfo_C2M_AddTalent.Size(m)
}
func (m *C2M_AddTalent) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_AddTalent.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_AddTalent proto.InternalMessageInfo

func (m *C2M_AddTalent) GetBladeId() int64 {
	if m != nil {
		return m.BladeId
	}
	return 0
}

func (m *C2M_AddTalent) GetTalentId() int32 {
	if m != nil {
		return m.TalentId
	}
	return 0
}

type C2M_QueryTalents struct {
	BladeId              int64    `protobuf:"varint,1,opt,name=BladeId,proto3" json:"BladeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QueryTalents) Reset()         { *m = C2M_QueryTalents{} }
func (m *C2M_QueryTalents) String() string { return proto.CompactTextString(m) }
func (*C2M_QueryTalents) ProtoMessage()    {}
func (*C2M_QueryTalents) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f418930e25cfdcc, []int{2}
}

func (m *C2M_QueryTalents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QueryTalents.Unmarshal(m, b)
}
func (m *C2M_QueryTalents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QueryTalents.Marshal(b, m, deterministic)
}
func (m *C2M_QueryTalents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QueryTalents.Merge(m, src)
}
func (m *C2M_QueryTalents) XXX_Size() int {
	return xxx_messageInfo_C2M_QueryTalents.Size(m)
}
func (m *C2M_QueryTalents) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QueryTalents.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QueryTalents proto.InternalMessageInfo

func (m *C2M_QueryTalents) GetBladeId() int64 {
	if m != nil {
		return m.BladeId
	}
	return 0
}

type M2C_TalentList struct {
	BladeId              int64     `protobuf:"varint,1,opt,name=BladeId,proto3" json:"BladeId,omitempty"`
	Talents              []*Talent `protobuf:"bytes,2,rep,name=Talents,proto3" json:"Talents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *M2C_TalentList) Reset()         { *m = M2C_TalentList{} }
func (m *M2C_TalentList) String() string { return proto.CompactTextString(m) }
func (*M2C_TalentList) ProtoMessage()    {}
func (*M2C_TalentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f418930e25cfdcc, []int{3}
}

func (m *M2C_TalentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_TalentList.Unmarshal(m, b)
}
func (m *M2C_TalentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_TalentList.Marshal(b, m, deterministic)
}
func (m *M2C_TalentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_TalentList.Merge(m, src)
}
func (m *M2C_TalentList) XXX_Size() int {
	return xxx_messageInfo_M2C_TalentList.Size(m)
}
func (m *M2C_TalentList) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_TalentList.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_TalentList proto.InternalMessageInfo

func (m *M2C_TalentList) GetBladeId() int64 {
	if m != nil {
		return m.BladeId
	}
	return 0
}

func (m *M2C_TalentList) GetTalents() []*Talent {
	if m != nil {
		return m.Talents
	}
	return nil
}

func init() {
	proto.RegisterType((*Talent)(nil), "game.Talent")
	proto.RegisterType((*C2M_AddTalent)(nil), "game.C2M_AddTalent")
	proto.RegisterType((*C2M_QueryTalents)(nil), "game.C2M_QueryTalents")
	proto.RegisterType((*M2C_TalentList)(nil), "game.M2C_TalentList")
}

func init() { proto.RegisterFile("game/talent.proto", fileDescriptor_0f418930e25cfdcc) }

var fileDescriptor_0f418930e25cfdcc = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2f, 0x49, 0xcc, 0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01,
	0x09, 0x29, 0x49, 0x70, 0xb1, 0x85, 0x80, 0x45, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x94, 0x5c, 0xb9, 0x78, 0x9d, 0x8d, 0x7c, 0xe3,
	0x1d, 0x53, 0x52, 0xa0, 0x0a, 0x24, 0xb8, 0xd8, 0x9d, 0x72, 0x12, 0x53, 0x52, 0x3d, 0x21, 0xaa,
	0x98, 0x83, 0x60, 0x5c, 0x21, 0x29, 0x2e, 0x0e, 0x88, 0x1a, 0xcf, 0x14, 0x09, 0x26, 0xb0, 0x01,
	0x70, 0xbe, 0x92, 0x0e, 0x97, 0x00, 0xc8, 0x98, 0xc0, 0xd2, 0xd4, 0xa2, 0x4a, 0x88, 0x60, 0x31,
	0x6e, 0x93, 0x94, 0x82, 0xb8, 0xf8, 0x7c, 0x8d, 0x9c, 0xe3, 0x21, 0x0a, 0x7d, 0x32, 0x8b, 0xf1,
	0xd9, 0xaa, 0xc6, 0xc5, 0x0e, 0x35, 0x50, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x47, 0x0f,
	0xe4, 0x25, 0x3d, 0x88, 0x60, 0x10, 0x4c, 0xd2, 0x49, 0x23, 0x4a, 0x2d, 0x3d, 0xb3, 0x24, 0xa3,
	0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x35, 0xb1, 0xb8, 0x44, 0x37, 0x35, 0x25, 0x35, 0x4f,
	0xbf, 0x38, 0xb5, 0xa8, 0x2c, 0xb5, 0x48, 0x1f, 0x1c, 0x1a, 0xfa, 0x20, 0x9d, 0x49, 0x6c, 0x60,
	0xb6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x78, 0x96, 0xbb, 0x2e, 0x01, 0x00, 0x00,
}
