// Code generated by protoc-gen-go. DO NOT EDIT.
// source: combat/combat.proto

package combat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	game "github.com/yokaiio/yokai_server/proto/game"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// unit scene att
type UnitAtt struct {
	UnitId               int64       `protobuf:"varint,1,opt,name=unitId,proto3" json:"unitId,omitempty"`
	UnitAttList          []*game.Att `protobuf:"bytes,2,rep,name=unitAttList,proto3" json:"unitAttList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UnitAtt) Reset()         { *m = UnitAtt{} }
func (m *UnitAtt) String() string { return proto.CompactTextString(m) }
func (*UnitAtt) ProtoMessage()    {}
func (*UnitAtt) Descriptor() ([]byte, []int) {
	return fileDescriptor_494bd6959abb49ec, []int{0}
}

func (m *UnitAtt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitAtt.Unmarshal(m, b)
}
func (m *UnitAtt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitAtt.Marshal(b, m, deterministic)
}
func (m *UnitAtt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitAtt.Merge(m, src)
}
func (m *UnitAtt) XXX_Size() int {
	return xxx_messageInfo_UnitAtt.Size(m)
}
func (m *UnitAtt) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitAtt.DiscardUnknown(m)
}

var xxx_messageInfo_UnitAtt proto.InternalMessageInfo

func (m *UnitAtt) GetUnitId() int64 {
	if m != nil {
		return m.UnitId
	}
	return 0
}

func (m *UnitAtt) GetUnitAttList() []*game.Att {
	if m != nil {
		return m.UnitAttList
	}
	return nil
}

type StartStageCombatReq struct {
	SceneId              int64      `protobuf:"varint,1,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	SceneType            int32      `protobuf:"varint,2,opt,name=sceneType,proto3" json:"sceneType,omitempty"`
	AttackId             int64      `protobuf:"varint,3,opt,name=attackId,proto3" json:"attackId,omitempty"`
	AttackUnitList       []*UnitAtt `protobuf:"bytes,4,rep,name=attackUnitList,proto3" json:"attackUnitList,omitempty"`
	DefenceId            int64      `protobuf:"varint,5,opt,name=defenceId,proto3" json:"defenceId,omitempty"`
	DefenceUnitList      []*UnitAtt `protobuf:"bytes,6,rep,name=defenceUnitList,proto3" json:"defenceUnitList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StartStageCombatReq) Reset()         { *m = StartStageCombatReq{} }
func (m *StartStageCombatReq) String() string { return proto.CompactTextString(m) }
func (*StartStageCombatReq) ProtoMessage()    {}
func (*StartStageCombatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_494bd6959abb49ec, []int{1}
}

func (m *StartStageCombatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStageCombatReq.Unmarshal(m, b)
}
func (m *StartStageCombatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStageCombatReq.Marshal(b, m, deterministic)
}
func (m *StartStageCombatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStageCombatReq.Merge(m, src)
}
func (m *StartStageCombatReq) XXX_Size() int {
	return xxx_messageInfo_StartStageCombatReq.Size(m)
}
func (m *StartStageCombatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStageCombatReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartStageCombatReq proto.InternalMessageInfo

func (m *StartStageCombatReq) GetSceneId() int64 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *StartStageCombatReq) GetSceneType() int32 {
	if m != nil {
		return m.SceneType
	}
	return 0
}

func (m *StartStageCombatReq) GetAttackId() int64 {
	if m != nil {
		return m.AttackId
	}
	return 0
}

func (m *StartStageCombatReq) GetAttackUnitList() []*UnitAtt {
	if m != nil {
		return m.AttackUnitList
	}
	return nil
}

func (m *StartStageCombatReq) GetDefenceId() int64 {
	if m != nil {
		return m.DefenceId
	}
	return 0
}

func (m *StartStageCombatReq) GetDefenceUnitList() []*UnitAtt {
	if m != nil {
		return m.DefenceUnitList
	}
	return nil
}

type StartStageCombatReply struct {
	SceneId              int64    `protobuf:"varint,1,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	AttackId             int64    `protobuf:"varint,2,opt,name=attackId,proto3" json:"attackId,omitempty"`
	DefenceId            int64    `protobuf:"varint,3,opt,name=defenceId,proto3" json:"defenceId,omitempty"`
	Result               bool     `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStageCombatReply) Reset()         { *m = StartStageCombatReply{} }
func (m *StartStageCombatReply) String() string { return proto.CompactTextString(m) }
func (*StartStageCombatReply) ProtoMessage()    {}
func (*StartStageCombatReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_494bd6959abb49ec, []int{2}
}

func (m *StartStageCombatReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStageCombatReply.Unmarshal(m, b)
}
func (m *StartStageCombatReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStageCombatReply.Marshal(b, m, deterministic)
}
func (m *StartStageCombatReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStageCombatReply.Merge(m, src)
}
func (m *StartStageCombatReply) XXX_Size() int {
	return xxx_messageInfo_StartStageCombatReply.Size(m)
}
func (m *StartStageCombatReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStageCombatReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartStageCombatReply proto.InternalMessageInfo

func (m *StartStageCombatReply) GetSceneId() int64 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *StartStageCombatReply) GetAttackId() int64 {
	if m != nil {
		return m.AttackId
	}
	return 0
}

func (m *StartStageCombatReply) GetDefenceId() int64 {
	if m != nil {
		return m.DefenceId
	}
	return 0
}

func (m *StartStageCombatReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*UnitAtt)(nil), "yokai_combat.UnitAtt")
	proto.RegisterType((*StartStageCombatReq)(nil), "yokai_combat.StartStageCombatReq")
	proto.RegisterType((*StartStageCombatReply)(nil), "yokai_combat.StartStageCombatReply")
}

func init() { proto.RegisterFile("combat/combat.proto", fileDescriptor_494bd6959abb49ec) }

var fileDescriptor_494bd6959abb49ec = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x7d, 0x6d, 0x1f, 0x85, 0x77, 0x79, 0x82, 0x19, 0x02, 0x69, 0x88, 0x0b, 0xac, 0x9b, 0x2e,
	0xcc, 0x34, 0xe2, 0xda, 0x18, 0x74, 0x45, 0xe2, 0xaa, 0xe0, 0xc6, 0x98, 0x90, 0xa1, 0x8c, 0x38,
	0x81, 0x7e, 0xd8, 0xde, 0x92, 0x74, 0xed, 0xc2, 0xbf, 0x6d, 0x3a, 0x53, 0xf9, 0xa8, 0x06, 0x57,
	0x33, 0xe7, 0xf6, 0xcc, 0xb9, 0xe7, 0xdc, 0x5e, 0xe8, 0xf8, 0x51, 0x30, 0x67, 0xe8, 0xaa, 0x83,
	0xc6, 0x49, 0x84, 0x11, 0xf9, 0x9f, 0x47, 0x2b, 0x26, 0x66, 0xaa, 0xd6, 0x6f, 0x2d, 0x59, 0xc0,
	0x5d, 0x86, 0xe5, 0x57, 0x7b, 0x0a, 0xf5, 0xc7, 0x50, 0xe0, 0x08, 0x91, 0xf4, 0xc0, 0xcc, 0x42,
	0x81, 0xe3, 0x85, 0xa5, 0x0d, 0x34, 0xc7, 0xf0, 0x4a, 0x44, 0xae, 0xa0, 0x99, 0x29, 0xca, 0x83,
	0x48, 0xd1, 0xd2, 0x07, 0x86, 0xd3, 0x1c, 0xb6, 0xa9, 0x92, 0x2d, 0xe4, 0xe8, 0x08, 0xd1, 0xdb,
	0xe7, 0xd8, 0x1f, 0x3a, 0x74, 0x26, 0xc8, 0x12, 0x9c, 0x20, 0x5b, 0xf2, 0x7b, 0xd9, 0xda, 0xe3,
	0x6f, 0xc4, 0x82, 0x7a, 0xea, 0xf3, 0x90, 0x6f, 0x7b, 0x7c, 0x41, 0x72, 0x06, 0xff, 0xe4, 0x75,
	0x9a, 0xc7, 0xdc, 0xd2, 0x07, 0x9a, 0x53, 0xf3, 0x76, 0x05, 0xd2, 0x87, 0x06, 0x43, 0x64, 0xfe,
	0x6a, 0xbc, 0xb0, 0x0c, 0xf9, 0x70, 0x8b, 0xc9, 0x0d, 0xb4, 0xd4, 0xbd, 0xc8, 0x21, 0x1d, 0xfe,
	0x95, 0x0e, 0xbb, 0x74, 0x3f, 0x38, 0x2d, 0x53, 0x7a, 0x15, 0x72, 0xd1, 0x78, 0xc1, 0x5f, 0x78,
	0xe8, 0x17, 0xa6, 0x6a, 0x52, 0x7b, 0x57, 0x20, 0xb7, 0xd0, 0x2e, 0xc1, 0x56, 0xdd, 0x3c, 0xa6,
	0x5e, 0x65, 0xdb, 0xef, 0x1a, 0x74, 0xbf, 0x4f, 0x22, 0x5e, 0xe7, 0x47, 0x66, 0xb1, 0x9f, 0x56,
	0xaf, 0xa4, 0x3d, 0xb0, 0x6b, 0x54, 0xed, 0xf6, 0xc0, 0x4c, 0x78, 0x9a, 0xad, 0x8b, 0x19, 0x68,
	0x4e, 0xc3, 0x2b, 0xd1, 0x30, 0x80, 0x13, 0xd5, 0x7a, 0xc2, 0x93, 0x8d, 0xf0, 0x39, 0x79, 0x86,
	0xd3, 0xaa, 0x2b, 0x72, 0x7e, 0x18, 0xe9, 0x87, 0xff, 0xd7, 0xbf, 0xf8, 0x8d, 0x12, 0xaf, 0x73,
	0xfb, 0xcf, 0x1d, 0x7d, 0xba, 0x5c, 0x0a, 0x7c, 0xcd, 0xe6, 0xd4, 0x8f, 0x02, 0x57, 0x3e, 0x11,
	0x91, 0x3a, 0x67, 0x29, 0x4f, 0x36, 0x3c, 0x71, 0xe5, 0xf6, 0x95, 0x8b, 0x3a, 0x37, 0x25, 0xba,
	0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x0d, 0xfd, 0xe8, 0xc0, 0x02, 0x00, 0x00,
}
