// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AccountInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MC_AccountLogon struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName          string   `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_AccountLogon) Reset()         { *m = MC_AccountLogon{} }
func (m *MC_AccountLogon) String() string { return proto.CompactTextString(m) }
func (*MC_AccountLogon) ProtoMessage()    {}
func (*MC_AccountLogon) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{1}
}

func (m *MC_AccountLogon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_AccountLogon.Unmarshal(m, b)
}
func (m *MC_AccountLogon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_AccountLogon.Marshal(b, m, deterministic)
}
func (m *MC_AccountLogon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_AccountLogon.Merge(m, src)
}
func (m *MC_AccountLogon) XXX_Size() int {
	return xxx_messageInfo_MC_AccountLogon.Size(m)
}
func (m *MC_AccountLogon) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_AccountLogon.DiscardUnknown(m)
}

var xxx_messageInfo_MC_AccountLogon proto.InternalMessageInfo

func (m *MC_AccountLogon) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *MC_AccountLogon) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

type MS_AccountLogon struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MS_AccountLogon) Reset()         { *m = MS_AccountLogon{} }
func (m *MS_AccountLogon) String() string { return proto.CompactTextString(m) }
func (*MS_AccountLogon) ProtoMessage()    {}
func (*MS_AccountLogon) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{2}
}

func (m *MS_AccountLogon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_AccountLogon.Unmarshal(m, b)
}
func (m *MS_AccountLogon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_AccountLogon.Marshal(b, m, deterministic)
}
func (m *MS_AccountLogon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_AccountLogon.Merge(m, src)
}
func (m *MS_AccountLogon) XXX_Size() int {
	return xxx_messageInfo_MS_AccountLogon.Size(m)
}
func (m *MS_AccountLogon) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_AccountLogon.DiscardUnknown(m)
}

var xxx_messageInfo_MS_AccountLogon proto.InternalMessageInfo

type MC_HeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_HeartBeat) Reset()         { *m = MC_HeartBeat{} }
func (m *MC_HeartBeat) String() string { return proto.CompactTextString(m) }
func (*MC_HeartBeat) ProtoMessage()    {}
func (*MC_HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{3}
}

func (m *MC_HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_HeartBeat.Unmarshal(m, b)
}
func (m *MC_HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_HeartBeat.Marshal(b, m, deterministic)
}
func (m *MC_HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_HeartBeat.Merge(m, src)
}
func (m *MC_HeartBeat) XXX_Size() int {
	return xxx_messageInfo_MC_HeartBeat.Size(m)
}
func (m *MC_HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_MC_HeartBeat proto.InternalMessageInfo

type MS_HeartBeat struct {
	Timestamp            uint32   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MS_HeartBeat) Reset()         { *m = MS_HeartBeat{} }
func (m *MS_HeartBeat) String() string { return proto.CompactTextString(m) }
func (*MS_HeartBeat) ProtoMessage()    {}
func (*MS_HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{4}
}

func (m *MS_HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MS_HeartBeat.Unmarshal(m, b)
}
func (m *MS_HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MS_HeartBeat.Marshal(b, m, deterministic)
}
func (m *MS_HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MS_HeartBeat.Merge(m, src)
}
func (m *MS_HeartBeat) XXX_Size() int {
	return xxx_messageInfo_MS_HeartBeat.Size(m)
}
func (m *MS_HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_MS_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_MS_HeartBeat proto.InternalMessageInfo

func (m *MS_HeartBeat) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type MC_AccountConnected struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_AccountConnected) Reset()         { *m = MC_AccountConnected{} }
func (m *MC_AccountConnected) String() string { return proto.CompactTextString(m) }
func (*MC_AccountConnected) ProtoMessage()    {}
func (*MC_AccountConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{5}
}

func (m *MC_AccountConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_AccountConnected.Unmarshal(m, b)
}
func (m *MC_AccountConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_AccountConnected.Marshal(b, m, deterministic)
}
func (m *MC_AccountConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_AccountConnected.Merge(m, src)
}
func (m *MC_AccountConnected) XXX_Size() int {
	return xxx_messageInfo_MC_AccountConnected.Size(m)
}
func (m *MC_AccountConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_AccountConnected.DiscardUnknown(m)
}

var xxx_messageInfo_MC_AccountConnected proto.InternalMessageInfo

func (m *MC_AccountConnected) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *MC_AccountConnected) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MC_AccountDisconnect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MC_AccountDisconnect) Reset()         { *m = MC_AccountDisconnect{} }
func (m *MC_AccountDisconnect) String() string { return proto.CompactTextString(m) }
func (*MC_AccountDisconnect) ProtoMessage()    {}
func (*MC_AccountDisconnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{6}
}

func (m *MC_AccountDisconnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MC_AccountDisconnect.Unmarshal(m, b)
}
func (m *MC_AccountDisconnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MC_AccountDisconnect.Marshal(b, m, deterministic)
}
func (m *MC_AccountDisconnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MC_AccountDisconnect.Merge(m, src)
}
func (m *MC_AccountDisconnect) XXX_Size() int {
	return xxx_messageInfo_MC_AccountDisconnect.Size(m)
}
func (m *MC_AccountDisconnect) XXX_DiscardUnknown() {
	xxx_messageInfo_MC_AccountDisconnect.DiscardUnknown(m)
}

var xxx_messageInfo_MC_AccountDisconnect proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AccountInfo)(nil), "yokai_account.AccountInfo")
	proto.RegisterType((*MC_AccountLogon)(nil), "yokai_account.MC_AccountLogon")
	proto.RegisterType((*MS_AccountLogon)(nil), "yokai_account.MS_AccountLogon")
	proto.RegisterType((*MC_HeartBeat)(nil), "yokai_account.MC_HeartBeat")
	proto.RegisterType((*MS_HeartBeat)(nil), "yokai_account.MS_HeartBeat")
	proto.RegisterType((*MC_AccountConnected)(nil), "yokai_account.MC_AccountConnected")
	proto.RegisterType((*MC_AccountDisconnect)(nil), "yokai_account.MC_AccountDisconnect")
}

func init() { proto.RegisterFile("account/account.proto", fileDescriptor_d66906c5773c9d08) }

var fileDescriptor_d66906c5773c9d08 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x10, 0xc0, 0x69, 0x15, 0xa1, 0xb7, 0x6e, 0xc3, 0xf8, 0x87, 0x3d, 0x28, 0xcc, 0x3c, 0xed, 0x41,
	0x57, 0xc4, 0x4f, 0xe0, 0xea, 0xc3, 0x06, 0xd6, 0x87, 0xf6, 0xcd, 0x97, 0x90, 0xa5, 0x71, 0x06,
	0x69, 0x6e, 0xb4, 0x37, 0xc1, 0x6f, 0x2f, 0xa6, 0x99, 0x51, 0x10, 0x7c, 0xba, 0xbb, 0x5f, 0xb8,
	0x5f, 0x2e, 0x17, 0x38, 0x93, 0x4a, 0xe1, 0xce, 0x52, 0xe6, 0xe3, 0x7c, 0xdb, 0x22, 0x21, 0x1b,
	0x7e, 0xe0, 0x9b, 0x34, 0xc2, 0x43, 0x7e, 0x0b, 0x83, 0xfb, 0x3e, 0x5d, 0xd9, 0x17, 0x64, 0x23,
	0x88, 0x4d, 0x3d, 0x89, 0xa6, 0xd1, 0xec, 0xa0, 0x8c, 0x4d, 0xcd, 0x18, 0x1c, 0x5a, 0xd9, 0xe8,
	0x49, 0x3c, 0x8d, 0x66, 0x49, 0xe9, 0x72, 0x5e, 0xc1, 0xb8, 0xc8, 0x85, 0xef, 0x7a, 0xc4, 0x0d,
	0x5a, 0x76, 0x09, 0xe0, 0x85, 0xe2, 0xbb, 0x3d, 0xf1, 0x64, 0x55, 0xb3, 0x2b, 0x48, 0xf7, 0xc7,
	0x3f, 0x6c, 0x03, 0xcf, 0x9e, 0xbe, 0xa4, 0xc7, 0x30, 0x2e, 0xaa, 0x5f, 0x52, 0x3e, 0x82, 0xb4,
	0xc8, 0xc5, 0x52, 0xcb, 0x96, 0x16, 0x5a, 0x12, 0xbf, 0x86, 0xb4, 0xa8, 0x42, 0xcd, 0x2e, 0x20,
	0x21, 0xd3, 0xe8, 0x8e, 0x64, 0xb3, 0x75, 0x77, 0x0e, 0xcb, 0x00, 0xf8, 0x12, 0x4e, 0xc2, 0x94,
	0x39, 0x5a, 0xab, 0x15, 0xe9, 0xfa, 0xbf, 0x49, 0xff, 0x7a, 0xef, 0x39, 0x9c, 0x06, 0xd3, 0x83,
	0xe9, 0x54, 0x2f, 0x5b, 0x64, 0xcf, 0x37, 0x1b, 0x43, 0xaf, 0xbb, 0xf5, 0x5c, 0x61, 0x93, 0xb9,
	0xb5, 0x1a, 0xec, 0xa3, 0xe8, 0x74, 0xfb, 0xae, 0xdb, 0xcc, 0xad, 0x7c, 0xff, 0x01, 0xeb, 0x23,
	0x57, 0xde, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x24, 0xee, 0x7e, 0x9a, 0x01, 0x00, 0x00,
}
