// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: server/mail/mail.proto

package mail

import (
	global "bitbucket.org/funplus/server/proto/global"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSystemMailRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverId int64           `protobuf:"varint,1,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`          // 收件人id
	Type       global.MailType `protobuf:"varint,2,opt,name=Type,proto3,enum=global.MailType" json:"Type,omitempty"` // 邮件类型
	Title      string          `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`                     // 邮件标题
	Content    string          `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                 // 邮件内容
}

func (x *CreateSystemMailRq) Reset() {
	*x = CreateSystemMailRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_mail_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSystemMailRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSystemMailRq) ProtoMessage() {}

func (x *CreateSystemMailRq) ProtoReflect() protoreflect.Message {
	mi := &file_server_mail_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSystemMailRq.ProtoReflect.Descriptor instead.
func (*CreateSystemMailRq) Descriptor() ([]byte, []int) {
	return file_server_mail_mail_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSystemMailRq) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *CreateSystemMailRq) GetType() global.MailType {
	if x != nil {
		return x.Type
	}
	return global.MailType_System
}

func (x *CreateSystemMailRq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSystemMailRq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMailRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"` // 错误码 0: 成功
	MailId    int64 `protobuf:"varint,2,opt,name=MailId,proto3" json:"MailId,omitempty"`       // 邮件id
}

func (x *CreateMailRs) Reset() {
	*x = CreateMailRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_mail_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMailRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMailRs) ProtoMessage() {}

func (x *CreateMailRs) ProtoReflect() protoreflect.Message {
	mi := &file_server_mail_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMailRs.ProtoReflect.Descriptor instead.
func (*CreateMailRs) Descriptor() ([]byte, []int) {
	return file_server_mail_mail_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMailRs) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateMailRs) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type CreatePlayerMailRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverId int64           `protobuf:"varint,1,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`          // 收件人id
	SenderId   int64           `protobuf:"varint,2,opt,name=SenderId,proto3" json:"SenderId,omitempty"`              // 发件人id
	Type       global.MailType `protobuf:"varint,3,opt,name=Type,proto3,enum=global.MailType" json:"Type,omitempty"` // 邮件类型
	SenderName string          `protobuf:"bytes,4,opt,name=SenderName,proto3" json:"SenderName,omitempty"`           // 发件人姓名
	Title      string          `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`                     // 邮件标题
	Content    string          `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                 // 邮件内容
}

func (x *CreatePlayerMailRq) Reset() {
	*x = CreatePlayerMailRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_mail_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayerMailRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerMailRq) ProtoMessage() {}

func (x *CreatePlayerMailRq) ProtoReflect() protoreflect.Message {
	mi := &file_server_mail_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerMailRq.ProtoReflect.Descriptor instead.
func (*CreatePlayerMailRq) Descriptor() ([]byte, []int) {
	return file_server_mail_mail_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlayerMailRq) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *CreatePlayerMailRq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *CreatePlayerMailRq) GetType() global.MailType {
	if x != nil {
		return x.Type
	}
	return global.MailType_System
}

func (x *CreatePlayerMailRq) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *CreatePlayerMailRq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePlayerMailRq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_server_mail_mail_proto protoreflect.FileDescriptor

var file_server_mail_mail_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x6d, 0x61,
	0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x13,
	0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x44, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0xc6, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32,
	0x95, 0x01, 0x0a, 0x0b, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x42, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d,
	0x61, 0x69, 0x6c, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x71, 0x1a, 0x12, 0x2e,
	0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x73, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x71, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x73, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x66, 0x75, 0x6e, 0x70, 0x6c, 0x75, 0x73,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_server_mail_mail_proto_rawDescOnce sync.Once
	file_server_mail_mail_proto_rawDescData = file_server_mail_mail_proto_rawDesc
)

func file_server_mail_mail_proto_rawDescGZIP() []byte {
	file_server_mail_mail_proto_rawDescOnce.Do(func() {
		file_server_mail_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_mail_mail_proto_rawDescData)
	})
	return file_server_mail_mail_proto_rawDescData
}

var file_server_mail_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_mail_mail_proto_goTypes = []interface{}{
	(*CreateSystemMailRq)(nil), // 0: mail.CreateSystemMailRq
	(*CreateMailRs)(nil),       // 1: mail.CreateMailRs
	(*CreatePlayerMailRq)(nil), // 2: mail.CreatePlayerMailRq
	(global.MailType)(0),       // 3: global.MailType
}
var file_server_mail_mail_proto_depIdxs = []int32{
	3, // 0: mail.CreateSystemMailRq.Type:type_name -> global.MailType
	3, // 1: mail.CreatePlayerMailRq.Type:type_name -> global.MailType
	0, // 2: mail.mailService.CreateSystemMail:input_type -> mail.CreateSystemMailRq
	2, // 3: mail.mailService.CreatePlayerMail:input_type -> mail.CreatePlayerMailRq
	1, // 4: mail.mailService.CreateSystemMail:output_type -> mail.CreateMailRs
	1, // 5: mail.mailService.CreatePlayerMail:output_type -> mail.CreateMailRs
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_mail_mail_proto_init() }
func file_server_mail_mail_proto_init() {
	if File_server_mail_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_mail_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSystemMailRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_mail_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMailRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_mail_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayerMailRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_mail_mail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_mail_mail_proto_goTypes,
		DependencyIndexes: file_server_mail_mail_proto_depIdxs,
		MessageInfos:      file_server_mail_mail_proto_msgTypes,
	}.Build()
	File_server_mail_mail_proto = out.File
	file_server_mail_mail_proto_rawDesc = nil
	file_server_mail_mail_proto_goTypes = nil
	file_server_mail_mail_proto_depIdxs = nil
}
